mutation AttachBeneficiaryToStructure($beneficiaryId: uuid!, $structureId: uuid!) {
	insert_beneficiary_structure_one(
		object: { beneficiaryId: $beneficiaryId, structureId: $structureId }
	) {
		id
	}
}
