mutation ImportBeneficiary(
	$firstname: String!
	$lastname: String!
	$dateOfBirth: date!
	$placeOfBirth: String
	$mobileNumber: String
	$email: citext
	$address1: String
	$address2: String
	$postalCode: String
	$city: String
	$workSituation: String
	$cafNumber: String
	$peNumber: String
	$rightRsa: String
	$rightAre: Boolean
	$rightAss: Boolean
	$rightBonus: Boolean
	$rightRqth: Boolean
	$geographicalArea: String
	$educationLevel: String
	$internalId: String
	$members: [notebook_member_insert_input!]!
	$structures: [beneficiary_structure_insert_input!]!
	$wantedJobs: [wanted_job_insert_input!]!
	$needOrientation: Boolean!
) {
	newNotebook: insert_notebook_one(
		object: {
			beneficiary: {
				data: {
					firstname: $firstname
					lastname: $lastname
					dateOfBirth: $dateOfBirth
					placeOfBirth: $placeOfBirth
					mobileNumber: $mobileNumber
					email: $email
					address1: $address1
					address2: $address2
					postalCode: $postalCode
					city: $city
					cafNumber: $cafNumber
					peNumber: $peNumber
					internalId: $internalId
					structures: { data: $structures }
					needOrientation: $needOrientation
				}
			}
			members: { data: $members }
			workSituation: $workSituation
			rightRsa: $rightRsa
			rightAre: $rightAre
			rightAss: $rightAss
			rightBonus: $rightBonus
			rightRqth: $rightRqth
			geographicalArea: $geographicalArea
			educationLevel: $educationLevel
			wantedJobs: { data: $wantedJobs }
		}
	) {
		id
	}
}
