-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object exposing (..)


type Account
    = Account


type Account_aggregate
    = Account_aggregate


type Account_aggregate_fields
    = Account_aggregate_fields


type Account_info
    = Account_info


type Account_info_aggregate
    = Account_info_aggregate


type Account_info_aggregate_fields
    = Account_info_aggregate_fields


type Account_info_max_fields
    = Account_info_max_fields


type Account_info_min_fields
    = Account_info_min_fields


type Account_max_fields
    = Account_max_fields


type Account_min_fields
    = Account_min_fields


type Account_mutation_response
    = Account_mutation_response


type Action_status
    = Action_status


type Action_status_aggregate
    = Action_status_aggregate


type Action_status_aggregate_fields
    = Action_status_aggregate_fields


type Action_status_max_fields
    = Action_status_max_fields


type Action_status_min_fields
    = Action_status_min_fields


type Action_status_mutation_response
    = Action_status_mutation_response


type Admin_cdb
    = Admin_cdb


type Admin_cdb_aggregate
    = Admin_cdb_aggregate


type Admin_cdb_aggregate_fields
    = Admin_cdb_aggregate_fields


type Admin_cdb_max_fields
    = Admin_cdb_max_fields


type Admin_cdb_min_fields
    = Admin_cdb_min_fields


type Admin_cdb_mutation_response
    = Admin_cdb_mutation_response


type Admin_structure
    = Admin_structure


type Admin_structure_aggregate
    = Admin_structure_aggregate


type Admin_structure_aggregate_fields
    = Admin_structure_aggregate_fields


type Admin_structure_max_fields
    = Admin_structure_max_fields


type Admin_structure_min_fields
    = Admin_structure_min_fields


type Admin_structure_mutation_response
    = Admin_structure_mutation_response


type Admin_structure_structure
    = Admin_structure_structure


type Admin_structure_structure_aggregate
    = Admin_structure_structure_aggregate


type Admin_structure_structure_aggregate_fields
    = Admin_structure_structure_aggregate_fields


type Admin_structure_structure_max_fields
    = Admin_structure_structure_max_fields


type Admin_structure_structure_min_fields
    = Admin_structure_structure_min_fields


type Admin_structure_structure_mutation_response
    = Admin_structure_structure_mutation_response


type Beneficiary
    = Beneficiary


type Beneficiary_aggregate
    = Beneficiary_aggregate


type Beneficiary_aggregate_fields
    = Beneficiary_aggregate_fields


type Beneficiary_max_fields
    = Beneficiary_max_fields


type Beneficiary_min_fields
    = Beneficiary_min_fields


type Beneficiary_mutation_response
    = Beneficiary_mutation_response


type Beneficiary_structure
    = Beneficiary_structure


type Beneficiary_structure_aggregate
    = Beneficiary_structure_aggregate


type Beneficiary_structure_aggregate_fields
    = Beneficiary_structure_aggregate_fields


type Beneficiary_structure_max_fields
    = Beneficiary_structure_max_fields


type Beneficiary_structure_min_fields
    = Beneficiary_structure_min_fields


type Beneficiary_structure_mutation_response
    = Beneficiary_structure_mutation_response


type Contract_type
    = Contract_type


type Contract_type_aggregate
    = Contract_type_aggregate


type Contract_type_aggregate_fields
    = Contract_type_aggregate_fields


type Contract_type_max_fields
    = Contract_type_max_fields


type Contract_type_min_fields
    = Contract_type_min_fields


type Contract_type_mutation_response
    = Contract_type_mutation_response


type Deployment
    = Deployment


type Deployment_aggregate
    = Deployment_aggregate


type Deployment_aggregate_fields
    = Deployment_aggregate_fields


type Deployment_max_fields
    = Deployment_max_fields


type Deployment_min_fields
    = Deployment_min_fields


type Deployment_mutation_response
    = Deployment_mutation_response


type Employment_type
    = Employment_type


type Employment_type_aggregate
    = Employment_type_aggregate


type Employment_type_aggregate_fields
    = Employment_type_aggregate_fields


type Employment_type_max_fields
    = Employment_type_max_fields


type Employment_type_min_fields
    = Employment_type_min_fields


type Employment_type_mutation_response
    = Employment_type_mutation_response


type External_data
    = External_data


type External_data_aggregate
    = External_data_aggregate


type External_data_aggregate_fields
    = External_data_aggregate_fields


type External_data_info
    = External_data_info


type External_data_info_aggregate
    = External_data_info_aggregate


type External_data_info_aggregate_fields
    = External_data_info_aggregate_fields


type External_data_info_max_fields
    = External_data_info_max_fields


type External_data_info_min_fields
    = External_data_info_min_fields


type External_data_info_mutation_response
    = External_data_info_mutation_response


type External_data_max_fields
    = External_data_max_fields


type External_data_min_fields
    = External_data_min_fields


type External_data_mutation_response
    = External_data_mutation_response


type External_source
    = External_source


type External_source_aggregate
    = External_source_aggregate


type External_source_aggregate_fields
    = External_source_aggregate_fields


type External_source_max_fields
    = External_source_max_fields


type External_source_min_fields
    = External_source_min_fields


type External_source_mutation_response
    = External_source_mutation_response


type Manager
    = Manager


type Manager_aggregate
    = Manager_aggregate


type Manager_aggregate_fields
    = Manager_aggregate_fields


type Manager_max_fields
    = Manager_max_fields


type Manager_min_fields
    = Manager_min_fields


type Manager_mutation_response
    = Manager_mutation_response


type NPSRatingOutput
    = NPSRatingOutput


type Notebook
    = Notebook


type Notebook_action
    = Notebook_action


type Notebook_action_aggregate
    = Notebook_action_aggregate


type Notebook_action_aggregate_fields
    = Notebook_action_aggregate_fields


type Notebook_action_max_fields
    = Notebook_action_max_fields


type Notebook_action_min_fields
    = Notebook_action_min_fields


type Notebook_action_mutation_response
    = Notebook_action_mutation_response


type Notebook_aggregate
    = Notebook_aggregate


type Notebook_aggregate_fields
    = Notebook_aggregate_fields


type Notebook_appointment
    = Notebook_appointment


type Notebook_appointment_aggregate
    = Notebook_appointment_aggregate


type Notebook_appointment_aggregate_fields
    = Notebook_appointment_aggregate_fields


type Notebook_appointment_max_fields
    = Notebook_appointment_max_fields


type Notebook_appointment_min_fields
    = Notebook_appointment_min_fields


type Notebook_appointment_mutation_response
    = Notebook_appointment_mutation_response


type Notebook_event
    = Notebook_event


type Notebook_event_aggregate
    = Notebook_event_aggregate


type Notebook_event_aggregate_fields
    = Notebook_event_aggregate_fields


type Notebook_event_max_fields
    = Notebook_event_max_fields


type Notebook_event_min_fields
    = Notebook_event_min_fields


type Notebook_event_mutation_response
    = Notebook_event_mutation_response


type Notebook_event_type
    = Notebook_event_type


type Notebook_event_type_aggregate
    = Notebook_event_type_aggregate


type Notebook_event_type_aggregate_fields
    = Notebook_event_type_aggregate_fields


type Notebook_event_type_max_fields
    = Notebook_event_type_max_fields


type Notebook_event_type_min_fields
    = Notebook_event_type_min_fields


type Notebook_event_type_mutation_response
    = Notebook_event_type_mutation_response


type Notebook_focus
    = Notebook_focus


type Notebook_focus_aggregate
    = Notebook_focus_aggregate


type Notebook_focus_aggregate_fields
    = Notebook_focus_aggregate_fields


type Notebook_focus_max_fields
    = Notebook_focus_max_fields


type Notebook_focus_min_fields
    = Notebook_focus_min_fields


type Notebook_focus_mutation_response
    = Notebook_focus_mutation_response


type Notebook_info
    = Notebook_info


type Notebook_info_aggregate
    = Notebook_info_aggregate


type Notebook_info_aggregate_fields
    = Notebook_info_aggregate_fields


type Notebook_info_max_fields
    = Notebook_info_max_fields


type Notebook_info_min_fields
    = Notebook_info_min_fields


type Notebook_info_mutation_response
    = Notebook_info_mutation_response


type Notebook_max_fields
    = Notebook_max_fields


type Notebook_member
    = Notebook_member


type Notebook_member_aggregate
    = Notebook_member_aggregate


type Notebook_member_aggregate_fields
    = Notebook_member_aggregate_fields


type Notebook_member_max_fields
    = Notebook_member_max_fields


type Notebook_member_min_fields
    = Notebook_member_min_fields


type Notebook_member_mutation_response
    = Notebook_member_mutation_response


type Notebook_min_fields
    = Notebook_min_fields


type Notebook_mutation_response
    = Notebook_mutation_response


type Notebook_public_view
    = Notebook_public_view


type Notebook_public_view_aggregate
    = Notebook_public_view_aggregate


type Notebook_public_view_aggregate_fields
    = Notebook_public_view_aggregate_fields


type Notebook_public_view_max_fields
    = Notebook_public_view_max_fields


type Notebook_public_view_min_fields
    = Notebook_public_view_min_fields


type Notebook_public_view_mutation_response
    = Notebook_public_view_mutation_response


type Notebook_situation
    = Notebook_situation


type Notebook_situation_aggregate
    = Notebook_situation_aggregate


type Notebook_situation_aggregate_fields
    = Notebook_situation_aggregate_fields


type Notebook_situation_max_fields
    = Notebook_situation_max_fields


type Notebook_situation_min_fields
    = Notebook_situation_min_fields


type Notebook_situation_mutation_response
    = Notebook_situation_mutation_response


type Notebook_target
    = Notebook_target


type Notebook_target_aggregate
    = Notebook_target_aggregate


type Notebook_target_aggregate_fields
    = Notebook_target_aggregate_fields


type Notebook_target_max_fields
    = Notebook_target_max_fields


type Notebook_target_min_fields
    = Notebook_target_min_fields


type Notebook_target_mutation_response
    = Notebook_target_mutation_response


type Nps_rating
    = Nps_rating


type Nps_rating_aggregate
    = Nps_rating_aggregate


type Nps_rating_aggregate_fields
    = Nps_rating_aggregate_fields


type Nps_rating_avg_fields
    = Nps_rating_avg_fields


type Nps_rating_dismissal
    = Nps_rating_dismissal


type Nps_rating_dismissal_aggregate
    = Nps_rating_dismissal_aggregate


type Nps_rating_dismissal_aggregate_fields
    = Nps_rating_dismissal_aggregate_fields


type Nps_rating_dismissal_max_fields
    = Nps_rating_dismissal_max_fields


type Nps_rating_dismissal_min_fields
    = Nps_rating_dismissal_min_fields


type Nps_rating_dismissal_mutation_response
    = Nps_rating_dismissal_mutation_response


type Nps_rating_max_fields
    = Nps_rating_max_fields


type Nps_rating_min_fields
    = Nps_rating_min_fields


type Nps_rating_mutation_response
    = Nps_rating_mutation_response


type Nps_rating_stddev_fields
    = Nps_rating_stddev_fields


type Nps_rating_stddev_pop_fields
    = Nps_rating_stddev_pop_fields


type Nps_rating_stddev_samp_fields
    = Nps_rating_stddev_samp_fields


type Nps_rating_sum_fields
    = Nps_rating_sum_fields


type Nps_rating_var_pop_fields
    = Nps_rating_var_pop_fields


type Nps_rating_var_samp_fields
    = Nps_rating_var_samp_fields


type Nps_rating_variance_fields
    = Nps_rating_variance_fields


type Orientation_manager
    = Orientation_manager


type Orientation_manager_aggregate
    = Orientation_manager_aggregate


type Orientation_manager_aggregate_fields
    = Orientation_manager_aggregate_fields


type Orientation_manager_max_fields
    = Orientation_manager_max_fields


type Orientation_manager_min_fields
    = Orientation_manager_min_fields


type Orientation_manager_mutation_response
    = Orientation_manager_mutation_response


type Orientation_request
    = Orientation_request


type Orientation_request_aggregate
    = Orientation_request_aggregate


type Orientation_request_aggregate_fields
    = Orientation_request_aggregate_fields


type Orientation_request_max_fields
    = Orientation_request_max_fields


type Orientation_request_min_fields
    = Orientation_request_min_fields


type Orientation_request_mutation_response
    = Orientation_request_mutation_response


type Orientation_system
    = Orientation_system


type Orientation_system_aggregate
    = Orientation_system_aggregate


type Orientation_system_aggregate_fields
    = Orientation_system_aggregate_fields


type Orientation_system_max_fields
    = Orientation_system_max_fields


type Orientation_system_min_fields
    = Orientation_system_min_fields


type Orientation_system_mutation_response
    = Orientation_system_mutation_response


type Orientation_type
    = Orientation_type


type Orientation_type_aggregate
    = Orientation_type_aggregate


type Orientation_type_aggregate_fields
    = Orientation_type_aggregate_fields


type Orientation_type_max_fields
    = Orientation_type_max_fields


type Orientation_type_min_fields
    = Orientation_type_min_fields


type Orientation_type_mutation_response
    = Orientation_type_mutation_response


type Professional
    = Professional


type Professional_aggregate
    = Professional_aggregate


type Professional_aggregate_fields
    = Professional_aggregate_fields


type Professional_max_fields
    = Professional_max_fields


type Professional_min_fields
    = Professional_min_fields


type Professional_mutation_response
    = Professional_mutation_response


type Professional_orientation_system
    = Professional_orientation_system


type Professional_orientation_system_aggregate
    = Professional_orientation_system_aggregate


type Professional_orientation_system_aggregate_fields
    = Professional_orientation_system_aggregate_fields


type Professional_orientation_system_max_fields
    = Professional_orientation_system_max_fields


type Professional_orientation_system_min_fields
    = Professional_orientation_system_min_fields


type Professional_orientation_system_mutation_response
    = Professional_orientation_system_mutation_response


type Professional_project
    = Professional_project


type Professional_project_aggregate
    = Professional_project_aggregate


type Professional_project_aggregate_fields
    = Professional_project_aggregate_fields


type Professional_project_avg_fields
    = Professional_project_avg_fields


type Professional_project_max_fields
    = Professional_project_max_fields


type Professional_project_min_fields
    = Professional_project_min_fields


type Professional_project_mutation_response
    = Professional_project_mutation_response


type Professional_project_stddev_fields
    = Professional_project_stddev_fields


type Professional_project_stddev_pop_fields
    = Professional_project_stddev_pop_fields


type Professional_project_stddev_samp_fields
    = Professional_project_stddev_samp_fields


type Professional_project_sum_fields
    = Professional_project_sum_fields


type Professional_project_var_pop_fields
    = Professional_project_var_pop_fields


type Professional_project_var_samp_fields
    = Professional_project_var_samp_fields


type Professional_project_variance_fields
    = Professional_project_variance_fields


type Ref_action
    = Ref_action


type Ref_action_aggregate
    = Ref_action_aggregate


type Ref_action_aggregate_fields
    = Ref_action_aggregate_fields


type Ref_action_max_fields
    = Ref_action_max_fields


type Ref_action_min_fields
    = Ref_action_min_fields


type Ref_action_mutation_response
    = Ref_action_mutation_response


type Ref_situation
    = Ref_situation


type Ref_situation_aggregate
    = Ref_situation_aggregate


type Ref_situation_aggregate_fields
    = Ref_situation_aggregate_fields


type Ref_situation_max_fields
    = Ref_situation_max_fields


type Ref_situation_min_fields
    = Ref_situation_min_fields


type Ref_situation_mutation_response
    = Ref_situation_mutation_response


type Ref_target
    = Ref_target


type Ref_target_aggregate
    = Ref_target_aggregate


type Ref_target_aggregate_fields
    = Ref_target_aggregate_fields


type Ref_target_max_fields
    = Ref_target_max_fields


type Ref_target_min_fields
    = Ref_target_min_fields


type Ref_target_mutation_response
    = Ref_target_mutation_response


type Ref_theme
    = Ref_theme


type Ref_theme_aggregate
    = Ref_theme_aggregate


type Ref_theme_aggregate_fields
    = Ref_theme_aggregate_fields


type Ref_theme_max_fields
    = Ref_theme_max_fields


type Ref_theme_min_fields
    = Ref_theme_min_fields


type Ref_theme_mutation_response
    = Ref_theme_mutation_response


type Role
    = Role


type Role_aggregate
    = Role_aggregate


type Role_aggregate_fields
    = Role_aggregate_fields


type Role_max_fields
    = Role_max_fields


type Role_min_fields
    = Role_min_fields


type Role_mutation_response
    = Role_mutation_response


type Rome_code
    = Rome_code


type Rome_code_aggregate
    = Rome_code_aggregate


type Rome_code_aggregate_fields
    = Rome_code_aggregate_fields


type Rome_code_max_fields
    = Rome_code_max_fields


type Rome_code_min_fields
    = Rome_code_min_fields


type Rome_code_mutation_response
    = Rome_code_mutation_response


type Rsa_closure_reason
    = Rsa_closure_reason


type Rsa_closure_reason_aggregate
    = Rsa_closure_reason_aggregate


type Rsa_closure_reason_aggregate_fields
    = Rsa_closure_reason_aggregate_fields


type Rsa_closure_reason_max_fields
    = Rsa_closure_reason_max_fields


type Rsa_closure_reason_min_fields
    = Rsa_closure_reason_min_fields


type Rsa_closure_reason_mutation_response
    = Rsa_closure_reason_mutation_response


type Rsa_suspension_reason
    = Rsa_suspension_reason


type Rsa_suspension_reason_aggregate
    = Rsa_suspension_reason_aggregate


type Rsa_suspension_reason_aggregate_fields
    = Rsa_suspension_reason_aggregate_fields


type Rsa_suspension_reason_max_fields
    = Rsa_suspension_reason_max_fields


type Rsa_suspension_reason_min_fields
    = Rsa_suspension_reason_min_fields


type Rsa_suspension_reason_mutation_response
    = Rsa_suspension_reason_mutation_response


type Structure
    = Structure


type Structure_aggregate
    = Structure_aggregate


type Structure_aggregate_fields
    = Structure_aggregate_fields


type Structure_max_fields
    = Structure_max_fields


type Structure_min_fields
    = Structure_min_fields


type Structure_mutation_response
    = Structure_mutation_response


type Structure_orientation_system
    = Structure_orientation_system


type Structure_orientation_system_aggregate
    = Structure_orientation_system_aggregate


type Structure_orientation_system_aggregate_fields
    = Structure_orientation_system_aggregate_fields


type Structure_orientation_system_max_fields
    = Structure_orientation_system_max_fields


type Structure_orientation_system_min_fields
    = Structure_orientation_system_min_fields


type Structure_orientation_system_mutation_response
    = Structure_orientation_system_mutation_response


type UpdateSocioProOutput
    = UpdateSocioProOutput
