mutation AddNotebookFocus(
	$notebookId: uuid!
	$situations: jsonb
	$theme: String!
	$linkedTo: String!
) {
	insert_notebook_focus_one(
		object: { notebookId: $notebookId, situations: $situations, theme: $theme, linkedTo: $linkedTo }
	) {
		id
	}
}

mutation UpdateNotebookFocus($id: uuid!, $situations: jsonb, $linkedTo: String!) {
	update_notebook_focus_by_pk(
		pk_columns: { id: $id }
		_set: { situations: $situations, linkedTo: $linkedTo }
	) {
		id
	}
}

mutation AddNotebookAction(
	$action: String!
	$targetId: uuid!
	$structureId: uuid!
	$status: String!
) {
	insert_notebook_action_one(
		object: { action: $action, structureId: $structureId, targetId: $targetId, status: $status }
	) {
		id
		target {
			id
		}
	}
}
