query GetNotebookFocusById($id: uuid!) {
  focus: notebook_focus_by_pk(id: $id) {
    id
    situations
    linkedTo
    targets(order_by: {creationDate: desc}) {
      target
      id
      actions(order_by: {creationDate: desc}) {
        id
        creationDate
        status
        action
        structure {
          id
          name
        }
        creator {
          id
          lastname
          firstname
        }
      }
    }
    theme
    professional {
      id
      position
      firstname
      lastname
      structureId
      structure {
        id
        name
        address1
        address2
        city
        postalCode
        website
      }
    }
    creationDate
  }
}

query GetRefSituations {
	refSituations: ref_situation {
		id
		description
		theme
	}
}

query GetRefSituationsByTheme($theme: String!) {
	refSituations: ref_situation(where: { theme: { _eq: $theme } }, order_by: { description: asc }) {
		id
		description
		theme
	}
}
