mutation UpdateNotebookFocus($id: uuid!, $situations: jsonb, $linkedTo: String!) {
	update_notebook_focus_by_pk(
		pk_columns: { id: $id }
		_set: { situations: $situations, linkedTo: $linkedTo }
	) {
		id
	}
}
