query SearchPublicNotebooks($filter: String) {
  notebooks: search_public_notebooks(
    args: { search: $filter }
    order_by: [
      { beneficiary: { lastname: asc_nulls_first } }
      { beneficiary: { firstname: asc_nulls_first } }
      { updated_at: desc_nulls_first }
    ]
  ) {
    id
    members {
      active
      accountId
      memberType
    }
    beneficiary {
      dateOfBirth
      firstname
      id
      lastname
      mobileNumber
      orientationRequest(order_by: { createdAt: desc }, limit: 1) {
        id
        status
        createdAt
        decidedAt
        requestedOrientationSystem {
          name
          orientationType
        }
      }
    }
    notebook {
      notebookInfo {
        orientationSystem {
          name
        }
      }
    }
  }
}
