query SearchNotebookMember(
  $accountId: uuid!
  $filter: String
  $visitDate: timestamptz_comparison_exp!
) {
  search_notebook_members(
    args: { search: $filter }
    where: { accountId: { _eq: $accountId }, lastVisitedAt: $visitDate, active: { _eq: true } }
    order_by: { lastModifiedAt: desc_nulls_first }
  ) {
    id
    notebook {
      id
      beneficiary {
        dateOfBirth
        firstname
        id
        lastname
        mobileNumber
        orientationRequest(order_by: { createdAt: desc }, limit: 1) {
          id
          status
          createdAt
          decidedAt
          requestedOrientationSystem {
            name
            orientationType
          }
        }
      }
    }
  }
}
