mutation AddNotebookMember($accountId: uuid!, $notebookId: uuid!) {
  newMember: insert_notebook_member_one(
    object: { accountId: $accountId, notebookId: $notebookId, memberType: "no_referent" }
  ) {
    id
  }
}
