-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."beneficiary_structure" add column "data" jsonb
--  not null default jsonb_build_object();
