query GetNotebooksAllAndRecent($afterDate: timestamptz_comparison_exp!) {
  all: notebook_aggregate {
		aggregate {
			count(distinct: false)
		}
  }
  recent: notebook_aggregate(
		where: {
			_and: [
				{ creationDate: $afterDate }
			]
		}
	) {
		aggregate {
			count(distinct: false)
		}
  }
  shared: notebook_aggregate {
    nodes {
      id
      members_aggregate {
        aggregate {
          count(distinct: false)
        }
      }
    }
  }
  structConnections: structure {
    id
    name
    city
    professionals_aggregate(where: { accounts: {lastLogin: $afterDate}}) {
      aggregate {
        count(distinct: false)
      }
    }
  }
}
