query GetAccount($accountId: uuid!) {
	account_by_pk(id: $accountId) {
		id
		onboardingDone
		confirmed
		username
		beneficiary {
			id
			firstname
			lastname
			email
			mobileNumber
			dateOfBirth
		}
		professional {
			id
			firstname
			lastname
			mobileNumber
			email
			position
			structure {
				id
				name
				address1
				address2
				postalCode
				city
			}
		}
	}
}
