query GetAccount($accountId: uuid!) {
	account_by_pk(id: $accountId) {
		id
		onboardingDone
		confirmed
		username
		beneficiary {
			firstname
			lastname
			email
			mobileNumber
			dateOfBirth
		}
		professional {
			firstname
			lastname
			mobileNumber
			email
			position
		}
	}
}
