mutation CreateRDVINotebookCreation(
  $accountId: uuid!
  $notebookId: uuid!
  $createdAt: timestamptz!
) {
  insert_rdvi_notebook_creations_one(
    object: { account_id: $accountId, created_at: $createdAt, notebook_id: $notebookId }
  ) {
    id
  }
}
