query GetAccountInfo($accessKey: String!) {
  account(where: { accessKey: { _eq: $accessKey }, deletedAt: { _is_null: true } }) {
    id
    type
    username
    beneficiaryId
    professionalId
    managerId
    adminStructureId
    orientationManagerId
    professional {
      structure {
        id
        deploymentId
      }
    }
    manager {
      deploymentId
    }
    adminStructure: admin_structure {
      deploymentId
    }
    orientationManager: orientation_manager {
      deploymentId
    }
    beneficiary {
      deploymentId
    }
  }
}
