query GetProfessionalsFromStructures($criteria: professional_bool_exp!) {
	professional(where: $criteria) {
		id
		firstname
		lastname
		mobileNumber
		position
		email
		structureId
		structure {
			id
			name
		}
	}
}
