mutation UpdateReferent($objects: [notebook_member_insert_input!]!, $beneficiaries: [uuid!]!) {
	update_beneficiary_structure(
		where: { beneficiaryId: { _in: $beneficiaries } }
		_set: { status: "done" }
	) {
		affected_rows
	}

	update_notebook_member(
		_set: { memberType: "no_referent" }
		where: { notebook: { beneficiaryId: { _in: $beneficiaries } } }
	) {
		affected_rows
	}

	insert_notebook_member(
		objects: $objects
		on_conflict: {
			constraint: notebook_member_notebook_id_account_id_key
			update_columns: [memberType, active]
		}
	) {
		affected_rows
	}
}

mutation UpdateReferentWithStructure(
	$objects: [notebook_member_insert_input!]!
	$beneficiaryStructureObjects: [beneficiary_structure_insert_input!]!
	$beneficiaries: [uuid!]!
) {
	delete_beneficiary_structure(where: { beneficiaryId: { _in: $beneficiaries } }) {
		affected_rows
	}
	insert_beneficiary_structure(objects: $beneficiaryStructureObjects) {
		affected_rows
	}

	update_notebook_member(
		_set: { memberType: "no_referent" }
		where: { memberType: { _eq: "referent" }, notebook: { beneficiaryId: { _in: $beneficiaries } } }
	) {
		affected_rows
	}

	insert_notebook_member(
		objects: $objects
		on_conflict: {
			constraint: notebook_member_notebook_id_account_id_key
			update_columns: [memberType, active]
		}
	) {
		affected_rows
	}
}

mutation RemoveReferent($notebooks: [uuid!]!) {
	update_notebook_member(
		_set: { memberType: "no_referent", active: false }
		where: { notebookId: { _in: $notebooks }, memberType: { _eq: "referent" } }
	) {
		affected_rows
	}
}
