mutation UpdateReferent(
	$objects: [notebook_member_insert_input!]!
	$structureId: uuid!
	$beneficiaries: [uuid!]!
) {
	update_beneficiary_structure(
		where: { beneficiaryId: { _in: $beneficiaries }, structureId: { _eq: $structureId } }
		_set: { status: "done" }
	) {
		affected_rows
	}
	insert_notebook_member(
		objects: $objects
		on_conflict: {
			constraint: notebook_member_notebook_id_professional_id_key
			update_columns: [memberType, active]
		}
	) {
		affected_rows
	}
}

mutation RemoveReferent($notebooks: [uuid!]!) {
	update_notebook_member(
		_set: { memberType: "no_referent", active: false }
		where: { notebookId: { _in: $notebooks } }
	) {
		affected_rows
	}
}
