query GetStructuresForDeployment($deployment: deployment_bool_exp = {}) {
  structure(where: { deployment: $deployment }, order_by: { name: asc }) {
    id
    siret
    name
    phone
    email
    postalCode
    city
    sensitive
    orientationSystems {
      orientationSystem {
        id
        name
        orientationType
      }
    }
  }
}
