mutation UpdateBeneficiaryPersonalInfo(
  $id: uuid!
  $accountId: uuid!
  $payload: beneficiary_set_input
) {
  updateMember: update_notebook_member(
    where: { notebook: { beneficiaryId: { _eq: $id } }, accountId: { _eq: $accountId } }
    _set: { lastModifiedAt: "now()" }
  ) {
    affected_rows
  }
  update: update_beneficiary_by_pk(pk_columns: { id: $id }, _set: $payload) {
    id
  }
}
