query GetProfessionalsForStructure($structureId: uuid!) {
	professional(
    where: { structureId: { _eq: $structureId }, account: { deletedAt: { _is_null: true } } }
    order_by: [{firstname: asc}, {lastname: asc}, {email: asc}]
  ) {
		id
		firstname
		lastname
		mobileNumber
		email
    position
    account {
      id
      onboardingDone
      notebooksWhereMember_aggregate {
        aggregate {
          count
        }
      }
    }
	}
}
