query GetProfessionalsForStructure($structureId: uuid!) {
	professional(where: { structureId: { _eq: $structureId } } order_by: [{firstname: asc}, {lastname: asc}, {email: asc}]) {
		id
		firstname
		lastname
		mobileNumber
		email
    position
    account {
      onboardingDone
      notebooksWhereMember_aggregate {
        aggregate {
          count
        }
      }
    }
	}
}
