query GetPendingBeneficiaries($structureId: uuid!) {
  structure_by_pk(id: $structureId) {
    beneficiaries(
      where: {
        status: { _eq: "pending" }
        beneficiary: {
          notebook: {
            _not: { members: { active: { _eq: true }, memberType: { _eq: "referent" } } }
          }
        }
      }
      order_by: { beneficiary: { lastname: asc } }
    ) {
      beneficiary {
        firstname
        lastname
        dateOfBirth
        notebook {
          id
        }
      }
    }
  }
}
