mutation UpdateSocioPro(
  $id: uuid!
  $workSituation: String
  $workSituationDate: date
  $workSituationEndDate: date
  $rightRqth: Boolean
  $educationLevel: String
  $lastJobEndedAt: date
  $professionalProjectsToAdd: [UpdateSocioProProfessionalProjectInsertInput!]!
  $professionalProjectIdsToDelete: [uuid!]!
  $professionalProjectsToUpdate: [UpdateSocioProProfessionalProjectSetInput!]!
  $situationsToAdd: [UpdateSocioProNotebookSituationInsertInput!]!
  $situationIdsToDelete: [uuid!]!
) {
  update_socio_pro(
    id: $id
    workSituation: $workSituation
    workSituationDate: $workSituationDate
    workSituationEndDate: $workSituationEndDate
    rightRqth: $rightRqth
    educationLevel: $educationLevel
    lastJobEndedAt: $lastJobEndedAt
    professionalProjectIdsToDelete: $professionalProjectIdsToDelete
    professionalProjectsToAdd: $professionalProjectsToAdd
    professionalProjectsToUpdate: $professionalProjectsToUpdate
    situationIdsToDelete: $situationIdsToDelete
    situationsToAdd: $situationsToAdd
  ) {
    id
  }
}
