mutation UpdateSocioPro(
  $id: uuid!
  $workSituation: String
  $workSituationDate: date
  $workSituationEndDate: date
  $rightRsa: String
  $rightAre: Boolean
  $rightAss: Boolean
  $rightRqth: Boolean
  $rightBonus: Boolean
  $geographicalArea: String
  $educationLevel: String
  $lastJobEndedAt: date
  $wantedJobs: [wanted_job_insert_input!]!
) {
  update: update_notebook_by_pk(
    pk_columns: { id: $id }
    _set: {
      workSituation: $workSituation
      workSituationDate: $workSituationDate
      workSituationEndDate: $workSituationEndDate
      rightRsa: $rightRsa
      rightAre: $rightAre
      rightAss: $rightAss
      rightRqth: $rightRqth
      rightBonus: $rightBonus
      geographicalArea: $geographicalArea
      educationLevel: $educationLevel
      lastJobEndedAt: $lastJobEndedAt
    }
  ) {
    id
  }
  delete_wanted_job(where: { notebook_id: { _eq: $id } }) {
    affected_rows
  }
  insert_wanted_job(objects: $wantedJobs) {
    affected_rows
  }
}
