mutation UpdateSocioPro(
  $id: uuid!
  $workSituation: String
  $workSituationDate: date
  $workSituationEndDate: date
  $rightRqth: Boolean
  $geographicalArea: String
  $educationLevel: String
  $lastJobEndedAt: date
  $wantedJobs: [wanted_job_insert_input!]!
  $addedNotebookFocus: [notebook_focus_insert_input!]!
  $updatedNotebookFocus: [notebook_focus_updates!]!
) {
  update: update_notebook_by_pk(
    pk_columns: { id: $id }
    _set: {
      workSituation: $workSituation
      workSituationDate: $workSituationDate
      workSituationEndDate: $workSituationEndDate
      rightRqth: $rightRqth
      geographicalArea: $geographicalArea
      educationLevel: $educationLevel
      lastJobEndedAt: $lastJobEndedAt
    }
  ) {
    id
  }
  delete_wanted_job(where: { notebook_id: { _eq: $id } }) {
    affected_rows
  }
  insert_wanted_job(objects: $wantedJobs) {
    affected_rows
  }
  insert_notebook_focus(objects: $addedNotebookFocus) {
    affected_rows
  }
  update_notebook_focus_many(updates: $updatedNotebookFocus) {
    affected_rows
  }
}
