query GetNotebookByBeneficiaryId($id: uuid!, $withOrientationRequests: Boolean = false) {
  notebook(where: { beneficiaryId: { _eq: $id } }) {
    ...notebookFragment
  }
}

query GetNotebookById($id: uuid!, $withOrientationRequests: Boolean = false) {
  notebook: notebook_by_pk(id: $id) {
    ...notebookFragment
  }
}

fragment notebookFragment on notebook {
  id
  beneficiaryId
  workSituation
  workSituationDate
  workSituationEndDate
  rightRqth
  contractType
  contractSignDate
  contractStartDate
  contractEndDate
  educationLevel
  lastJobEndedAt
  professionalProjects {
    id
    rome_code {
      id
      label
    }
    contract_type {
      id
      label
    }
    employment_type {
      id
      label
    }
    hourlyRate
    mobilityRadius
    updatedAt
    createdAt
    updater {
      orientation_manager {
        firstname
        lastname
      }
      professional {
        firstname
        lastname
        structure {
          name
        }
      }
    }
  }
  notebookInfo {
    needOrientation
    orientationReason
  }
  beneficiary {
    address1
    address2
    cafNumber
    city
    dateOfBirth
    email
    firstname
    id
    lastname
    mobileNumber
    peNumber
    postalCode
    rightAre
    rightAss
    rightBonus
    rightRsa
    externalDataInfos {
      external_data_id
      externalData {
        data
        source
      }
    }
    orientationRequest(order_by: { createdAt: desc }, limit: 1)
      @include(if: $withOrientationRequests) {
      id
      createdAt
      decidedAt
      requestedOrientationSystem {
        name
        orientationType
      }
      beneficiary {
        id
        notebook {
          id
        }
      }
    }
  }
  members(where: { active: { _eq: true } }, order_by: { lastModifiedAt: desc_nulls_last }) {
    id
    memberType
    lastModifiedAt
    lastVisitedAt
    account {
      type
      orientation_manager {
        id
        lastname
        firstname
        email
        phoneNumbers
      }
      professional {
        id
        lastname
        firstname
        position
        email
        mobileNumber
        structure {
          id
          name
          address1
          address2
          postalCode
          city
        }
      }
    }
  }
  situations(where: { deletedAt: { _is_null: true } }, order_by: { createdAt: desc }) {
    id
    refSituation {
      id
      theme
      description
    }
    createdAt
    creator {
      orientation_manager {
        firstname
        lastname
      }
      professional {
        firstname
        lastname
        structure {
          name
        }
      }
    }
  }
  focuses(order_by: { createdAt: desc_nulls_first }) {
    theme
    createdAt
    creator {
      orientation_manager {
        firstname
        lastname
      }
      professional {
        firstname
        lastname
        structure {
          name
        }
      }
    }
    targets(where: { status: { _eq: "in_progress" } }, order_by: { createdAt: desc_nulls_first }) {
      target
      createdAt
      creator {
        orientation_manager {
          firstname
          lastname
        }
        professional {
          firstname
          lastname
          structure {
            name
          }
        }
      }
      actions(where: { status: { _eq: in_progress } }, order_by: { createdAt: desc_nulls_first }) {
        action
        createdAt
        status
        creator {
          orientation_manager {
            firstname
            lastname
          }
          professional {
            firstname
            lastname
            structure {
              name
            }
          }
        }
      }
    }
  }
}
