query GetNotebookByBeneficiaryId($id: uuid!, $withOrientationRequests: Boolean = false) {
  notebook(where: { beneficiaryId: { _eq: $id } }) {
    ...notebookFragment
  }
}

query GetNotebookById($id: uuid!, $withOrientationRequests: Boolean = false) {
  notebook: notebook_by_pk(id: $id) {
    ...notebookFragment
  }
}

fragment notebookFragment on notebook {
  id
  workSituation
  workSituationDate
  workSituationEndDate
  rightAre
  rightAss
  rightRsa
  rightRqth
  rightBonus
  contractType
  contractSignDate
  contractStartDate
  contractEndDate
  educationLevel
  wantedJobs {
    rome_code {
      id
      label
    }
  }
  notebookInfo {
    needOrientation
  }
  geographicalArea
  beneficiary {
    address1
    address2
    cafNumber
    city
    dateOfBirth
    email
    firstname
    id
    lastname
    mobileNumber
    peNumber
    postalCode
    orientationRequest(order_by: {createdAt: desc}, limit: 1) @include(if: $withOrientationRequests) {
      id
      createdAt
      decidedAt
      requestedOrientationType {
        label
      }
      beneficiary {
        id
        notebook {
          id
        }
      }
    }
  }
  members(where: { active: { _eq: true } }, order_by: { lastModifiedAt: desc_nulls_last }) {
    id
    memberType
    lastModifiedAt
    lastVisitedAt
    account {
      type
      orientation_manager {
        id
        lastname
        firstname
        email
        phoneNumbers
      }
      professional {
        id
        lastname
        firstname
        position
        email
        mobileNumber
        structure {
          id
          name
          address1
          address2
          postalCode
          city
        }
      }
    }
  }
  focuses(order_by: { createdAt: desc_nulls_first }) {
    theme
    situations
    creator {
      orientation_manager {
        firstname
        lastname
      }
      professional {
        firstname
        lastname
        structure {
          name
        }
      }
    }
    targets(where: { status: { _eq: "in_progress" } }, order_by: { createdAt: desc_nulls_first }) {
      target
      createdAt
      creator {
        orientation_manager {
          firstname
          lastname
        }
        professional {
          firstname
          lastname
          structure {
            name
          }
        }
      }
      actions(
        where: { status: { _eq: "in_progress" } }
        order_by: { createdAt: desc_nulls_first }
      ) {
        action
        createdAt
        status
        creator {
          orientation_manager {
            firstname
            lastname
          }
          professional {
            firstname
            lastname
            structure {
              name
            }
          }
        }
      }
    }
  }
}
