query GetAccountsSummary {
	proConfirmed: account(where: { type: { _eq: "professional" }, confirmed: { _eq: true } }) {
		id
		professional {
			id
			firstname
			lastname
			position
			structure {
				name
			}
		}
	}
	proUnconfirmed: account(where: { type: { _eq: "professional" }, confirmed: { _eq: false } }) {
		id
		professional {
			id
			firstname
			lastname
			position
			structure {
				name
			}
		}
	}
	beneficiaryConfirmed: account(where: { type: { _eq: "beneficiary" }, confirmed: { _eq: true } }) {
		id
		beneficiary {
			id
			firstname
			lastname
		}
	}
	beneficiaryUnconfirmed: account(
		where: { type: { _eq: "beneficiary" }, confirmed: { _eq: false } }
	) {
		id
		beneficiary {
			id
			firstname
			lastname
		}
	}
}
