query GetDeploymentNotebooks($deploymentId: uuid!) {
  deployment: deployment_by_pk(id: $deploymentId) {
    label
    id
  }
  notebooks: notebook(where: { beneficiary: { deploymentId: { _eq: $deploymentId } } }) {
    id
    notebookInfo {
      needOrientation
    }
    beneficiary {
      firstname
      lastname
      orientationRequest(order_by: {createdAt: desc}, limit: 1) {
        id
        createdAt
        decidedAt
        requestedOrientationType {
          label
        }
        beneficiary {
          id
          notebook {
            id
          }
        }
      }
    }
  }
}
