query GetDeploymentById($id: uuid!) {
  deployment: deployment_by_pk(id: $id) {
    id
    label
    config
    managers(order_by: { createdAt: asc }) {
      id
      firstname
      lastname
      email
      account {
        onboardingDone
      }
    }
    beneficiaries_aggregate {
      aggregate {
        count
      }
    }
    structures_aggregate {
      aggregate {
        count
      }
    }
  }
  professional_aggregate(
    where: { account: { deletedAt: { _is_null: true } }, structure: { deploymentId: { _eq: $id } } }
  ) {
    aggregate {
      count
    }
  }
}
