mutation AddNotebookMemberWithBeneficiaryStructureUpdate($member: notebook_member_insert_input!) {
  insert_notebook_member_one(
    object: $member
  ) {
    notebook {
      beneficiaryId
    }
  }
}
