mutation AddNotebookMemberWithBeneficiaryStructureUpdate($member: notebook_member_insert_input!) {
  insert_notebook_member_one(
    object: $member
    on_conflict: { constraint: notebook_member_notebook_id_account_id_key, update_columns: active }
  ) {
    notebook {
      beneficiaryId
    }
  }
}
