query GetNotebookForBeneficiary($array: [notebook_bool_exp!]) {
  notebook(where: { _or: $array }) {
    id
    beneficiaryId
    beneficiary {
      firstname
      lastname
      dateOfBirth
      structures(where: { status: { _eq: "current" } }) {
        structureId
      }
    }
  }
}
