mutation ImportStructure(
  $name: citext!
  $phone: String
  $email: String
  $address1: String
  $address2: String
  $postalCode: String
  $city: String
  $website: String
  $siret: String
  $shortDesc: String
  $adminEmail: citext
  $firstname: String
  $lastname: String
  $position: String
  $phoneNumbers: String
  $forceUpdate: Boolean
  $sendAccountEmail: Boolean
) {
  structure: insertStructureWithAdmin(
    data: {
      structure: {
        name: $name
        phone: $phone
        email: $email
        address1: $address1
        address2: $address2
        postalCode: $postalCode
        city: $city
        website: $website
        siret: $siret
        shortDesc: $shortDesc
      }
      adminStructure: {
        adminEmail: $adminEmail
        firstname: $firstname
        lastname: $lastname
        position: $position
        phoneNumbers: $phoneNumbers
      }
      forceUpdate: $forceUpdate
      sendAccountEmail: $sendAccountEmail
    }
  ) {
    id
    # name
    # phone
    # email
    # address1
    # address2
    # postalCode
    # city
    # website
    # siret
    # shortDesc
  }
}
