-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."account" add column "refresh_token_date" timestamptz
--  null default now();
