-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select "account\_aggregate\_bool\_exp\_bool\_or\_arguments\_columns" columns of table "account"

  - Confirmed - column name
  - OnboardingDone - column name

-}
type Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns
    = Confirmed
    | OnboardingDone


list : List Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns
list =
    [ Confirmed, OnboardingDone ]


decoder : Decoder Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "confirmed" ->
                        Decode.succeed Confirmed

                    "onboardingDone" ->
                        Decode.succeed OnboardingDone

                    _ ->
                        Decode.fail ("Invalid Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns -> String
toString enum____ =
    case enum____ of
        Confirmed ->
            "confirmed"

        OnboardingDone ->
            "onboardingDone"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Account_select_column_account_aggregate_bool_exp_bool_or_arguments_columns
fromString enumString____ =
    case enumString____ of
        "confirmed" ->
            Just Confirmed

        "onboardingDone" ->
            Just OnboardingDone

        _ ->
            Nothing
