-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Action_status_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "action\_status"

  - Action\_status\_pkey - unique or primary key constraint on columns "status"

-}
type Action_status_constraint
    = Action_status_pkey


list : List Action_status_constraint
list =
    [ Action_status_pkey ]


decoder : Decoder Action_status_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "action_status_pkey" ->
                        Decode.succeed Action_status_pkey

                    _ ->
                        Decode.fail ("Invalid Action_status_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Action_status_constraint -> String
toString enum____ =
    case enum____ of
        Action_status_pkey ->
            "action_status_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Action_status_constraint
fromString enumString____ =
    case enumString____ of
        "action_status_pkey" ->
            Just Action_status_pkey

        _ ->
            Nothing
