-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Contract_type_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "contract\_type"

  - Contract\_type\_pkey - unique or primary key constraint on columns "id"

-}
type Contract_type_constraint
    = Contract_type_pkey


list : List Contract_type_constraint
list =
    [ Contract_type_pkey ]


decoder : Decoder Contract_type_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "contract_type_pkey" ->
                        Decode.succeed Contract_type_pkey

                    _ ->
                        Decode.fail ("Invalid Contract_type_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Contract_type_constraint -> String
toString enum____ =
    case enum____ of
        Contract_type_pkey ->
            "contract_type_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Contract_type_constraint
fromString enumString____ =
    case enumString____ of
        "contract_type_pkey" ->
            Just Contract_type_pkey

        _ ->
            Nothing
