-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Deployment_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "deployment"

  - Deployment\_pkey - unique or primary key constraint on columns "id"

-}
type Deployment_constraint
    = Deployment_pkey


list : List Deployment_constraint
list =
    [ Deployment_pkey ]


decoder : Decoder Deployment_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "deployment_pkey" ->
                        Decode.succeed Deployment_pkey

                    _ ->
                        Decode.fail ("Invalid Deployment_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Deployment_constraint -> String
toString enum____ =
    case enum____ of
        Deployment_pkey ->
            "deployment_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Deployment_constraint
fromString enumString____ =
    case enumString____ of
        "deployment_pkey" ->
            Just Deployment_pkey

        _ ->
            Nothing
