-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.External_data_info_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "external\_data\_info"

  - Beneficiary\_id - column name
  - Created\_at - column name
  - External\_data\_id - column name
  - Professional\_id - column name
  - Updated\_at - column name

-}
type External_data_info_select_column
    = Beneficiary_id
    | Created_at
    | External_data_id
    | Professional_id
    | Updated_at


list : List External_data_info_select_column
list =
    [ Beneficiary_id, Created_at, External_data_id, Professional_id, Updated_at ]


decoder : Decoder External_data_info_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "beneficiary_id" ->
                        Decode.succeed Beneficiary_id

                    "created_at" ->
                        Decode.succeed Created_at

                    "external_data_id" ->
                        Decode.succeed External_data_id

                    "professional_id" ->
                        Decode.succeed Professional_id

                    "updated_at" ->
                        Decode.succeed Updated_at

                    _ ->
                        Decode.fail ("Invalid External_data_info_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : External_data_info_select_column -> String
toString enum____ =
    case enum____ of
        Beneficiary_id ->
            "beneficiary_id"

        Created_at ->
            "created_at"

        External_data_id ->
            "external_data_id"

        Professional_id ->
            "professional_id"

        Updated_at ->
            "updated_at"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe External_data_info_select_column
fromString enumString____ =
    case enumString____ of
        "beneficiary_id" ->
            Just Beneficiary_id

        "created_at" ->
            Just Created_at

        "external_data_id" ->
            Just External_data_id

        "professional_id" ->
            Just Professional_id

        "updated_at" ->
            Just Updated_at

        _ ->
            Nothing
