-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Notebook_target_update_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "notebook\_target"

  - CreatedAt - column name
  - CreatorId - column name
  - FocusId - column name
  - Id - column name
  - Status - column name
  - Target - column name
  - UpdatedAt - column name

-}
type Notebook_target_update_column
    = CreatedAt
    | CreatorId
    | FocusId
    | Id
    | Status
    | Target
    | UpdatedAt


list : List Notebook_target_update_column
list =
    [ CreatedAt, CreatorId, FocusId, Id, Status, Target, UpdatedAt ]


decoder : Decoder Notebook_target_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "creatorId" ->
                        Decode.succeed CreatorId

                    "focusId" ->
                        Decode.succeed FocusId

                    "id" ->
                        Decode.succeed Id

                    "status" ->
                        Decode.succeed Status

                    "target" ->
                        Decode.succeed Target

                    "updatedAt" ->
                        Decode.succeed UpdatedAt

                    _ ->
                        Decode.fail ("Invalid Notebook_target_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Notebook_target_update_column -> String
toString enum____ =
    case enum____ of
        CreatedAt ->
            "createdAt"

        CreatorId ->
            "creatorId"

        FocusId ->
            "focusId"

        Id ->
            "id"

        Status ->
            "status"

        Target ->
            "target"

        UpdatedAt ->
            "updatedAt"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Notebook_target_update_column
fromString enumString____ =
    case enumString____ of
        "createdAt" ->
            Just CreatedAt

        "creatorId" ->
            Just CreatorId

        "focusId" ->
            Just FocusId

        "id" ->
            Just Id

        "status" ->
            Just Status

        "target" ->
            Just Target

        "updatedAt" ->
            Just UpdatedAt

        _ ->
            Nothing
