-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Notebook_public_view_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "notebook\_public\_view"

  - Beneficiary\_id - column name
  - Created\_at - column name
  - Id - column name
  - Updated\_at - column name

-}
type Notebook_public_view_select_column
    = Beneficiary_id
    | Created_at
    | Id
    | Updated_at


list : List Notebook_public_view_select_column
list =
    [ Beneficiary_id, Created_at, Id, Updated_at ]


decoder : Decoder Notebook_public_view_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "beneficiary_id" ->
                        Decode.succeed Beneficiary_id

                    "created_at" ->
                        Decode.succeed Created_at

                    "id" ->
                        Decode.succeed Id

                    "updated_at" ->
                        Decode.succeed Updated_at

                    _ ->
                        Decode.fail ("Invalid Notebook_public_view_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Notebook_public_view_select_column -> String
toString enum____ =
    case enum____ of
        Beneficiary_id ->
            "beneficiary_id"

        Created_at ->
            "created_at"

        Id ->
            "id"

        Updated_at ->
            "updated_at"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Notebook_public_view_select_column
fromString enumString____ =
    case enumString____ of
        "beneficiary_id" ->
            Just Beneficiary_id

        "created_at" ->
            Just Created_at

        "id" ->
            Just Id

        "updated_at" ->
            Just Updated_at

        _ ->
            Nothing
