-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Notebook_situation_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "notebook\_situation"

  - Notebook\_situation\_notebook\_id\_situation\_id\_deleted\_at\_key - unique or primary key constraint on columns "deleted\_at", "notebook\_id", "situation\_id"
  - Notebook\_situation\_pkey - unique or primary key constraint on columns "id"

-}
type Notebook_situation_constraint
    = Notebook_situation_notebook_id_situation_id_deleted_at_key
    | Notebook_situation_pkey


list : List Notebook_situation_constraint
list =
    [ Notebook_situation_notebook_id_situation_id_deleted_at_key, Notebook_situation_pkey ]


decoder : Decoder Notebook_situation_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "notebook_situation_notebook_id_situation_id_deleted_at_key" ->
                        Decode.succeed Notebook_situation_notebook_id_situation_id_deleted_at_key

                    "notebook_situation_pkey" ->
                        Decode.succeed Notebook_situation_pkey

                    _ ->
                        Decode.fail ("Invalid Notebook_situation_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Notebook_situation_constraint -> String
toString enum____ =
    case enum____ of
        Notebook_situation_notebook_id_situation_id_deleted_at_key ->
            "notebook_situation_notebook_id_situation_id_deleted_at_key"

        Notebook_situation_pkey ->
            "notebook_situation_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Notebook_situation_constraint
fromString enumString____ =
    case enumString____ of
        "notebook_situation_notebook_id_situation_id_deleted_at_key" ->
            Just Notebook_situation_notebook_id_situation_id_deleted_at_key

        "notebook_situation_pkey" ->
            Just Notebook_situation_pkey

        _ ->
            Nothing
