-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Professional_project_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "professional\_project"

  - Notebook\_id\_rome\_code\_id\_null\_idx - unique or primary key constraint on columns "notebook\_id"
  - Professional\_project\_pkey - unique or primary key constraint on columns "id"

-}
type Professional_project_constraint
    = Notebook_id_rome_code_id_null_idx
    | Professional_project_pkey


list : List Professional_project_constraint
list =
    [ Notebook_id_rome_code_id_null_idx, Professional_project_pkey ]


decoder : Decoder Professional_project_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "notebook_id_rome_code_id_null_idx" ->
                        Decode.succeed Notebook_id_rome_code_id_null_idx

                    "professional_project_pkey" ->
                        Decode.succeed Professional_project_pkey

                    _ ->
                        Decode.fail ("Invalid Professional_project_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Professional_project_constraint -> String
toString enum____ =
    case enum____ of
        Notebook_id_rome_code_id_null_idx ->
            "notebook_id_rome_code_id_null_idx"

        Professional_project_pkey ->
            "professional_project_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Professional_project_constraint
fromString enumString____ =
    case enumString____ of
        "notebook_id_rome_code_id_null_idx" ->
            Just Notebook_id_rome_code_id_null_idx

        "professional_project_pkey" ->
            Just Professional_project_pkey

        _ ->
            Nothing
