-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Ref_theme_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "ref\_theme"

  - Label - column name
  - Name - column name

-}
type Ref_theme_select_column
    = Label
    | Name


list : List Ref_theme_select_column
list =
    [ Label, Name ]


decoder : Decoder Ref_theme_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "label" ->
                        Decode.succeed Label

                    "name" ->
                        Decode.succeed Name

                    _ ->
                        Decode.fail ("Invalid Ref_theme_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Ref_theme_select_column -> String
toString enum____ =
    case enum____ of
        Label ->
            "label"

        Name ->
            "name"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Ref_theme_select_column
fromString enumString____ =
    case enumString____ of
        "label" ->
            Just Label

        "name" ->
            Just Name

        _ ->
            Nothing
