-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Ref_action_constraint exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "ref\_action"

  - Ref\_action\_pkey - unique or primary key constraint on columns "id"

-}
type Ref_action_constraint
    = Ref_action_pkey


list : List Ref_action_constraint
list =
    [ Ref_action_pkey ]


decoder : Decoder Ref_action_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ref_action_pkey" ->
                        Decode.succeed Ref_action_pkey

                    _ ->
                        Decode.fail ("Invalid Ref_action_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Ref_action_constraint -> String
toString enum____ =
    case enum____ of
        Ref_action_pkey ->
            "ref_action_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Ref_action_constraint
fromString enumString____ =
    case enumString____ of
        "ref_action_pkey" ->
            Just Ref_action_pkey

        _ ->
            Nothing
