-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.Structure_orientation_system_select_column exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "structure\_orientation\_system"

  - CreatedAt - column name
  - Id - column name
  - OrientationSystemId - column name
  - StructureId - column name

-}
type Structure_orientation_system_select_column
    = CreatedAt
    | Id
    | OrientationSystemId
    | StructureId


list : List Structure_orientation_system_select_column
list =
    [ CreatedAt, Id, OrientationSystemId, StructureId ]


decoder : Decoder Structure_orientation_system_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "createdAt" ->
                        Decode.succeed CreatedAt

                    "id" ->
                        Decode.succeed Id

                    "orientationSystemId" ->
                        Decode.succeed OrientationSystemId

                    "structureId" ->
                        Decode.succeed StructureId

                    _ ->
                        Decode.fail ("Invalid Structure_orientation_system_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : Structure_orientation_system_select_column -> String
toString enum____ =
    case enum____ of
        CreatedAt ->
            "createdAt"

        Id ->
            "id"

        OrientationSystemId ->
            "orientationSystemId"

        StructureId ->
            "structureId"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Structure_orientation_system_select_column
fromString enumString____ =
    case enumString____ of
        "createdAt" ->
            Just CreatedAt

        "id" ->
            Just Id

        "orientationSystemId" ->
            Just OrientationSystemId

        "structureId" ->
            Just StructureId

        _ ->
            Nothing
