-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Enum.UpdateSocioProEmploymentTypeEnum exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Full\_time - Temps plein
  - Part\_time - Temps partiel

-}
type UpdateSocioProEmploymentTypeEnum
    = Full_time
    | Part_time


list : List UpdateSocioProEmploymentTypeEnum
list =
    [ Full_time, Part_time ]


decoder : Decoder UpdateSocioProEmploymentTypeEnum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "full_time" ->
                        Decode.succeed Full_time

                    "part_time" ->
                        Decode.succeed Part_time

                    _ ->
                        Decode.fail ("Invalid UpdateSocioProEmploymentTypeEnum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : UpdateSocioProEmploymentTypeEnum -> String
toString enum____ =
    case enum____ of
        Full_time ->
            "full_time"

        Part_time ->
            "part_time"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe UpdateSocioProEmploymentTypeEnum
fromString enumString____ =
    case enumString____ of
        "full_time" ->
            Just Full_time

        "part_time" ->
            Just Part_time

        _ ->
            Nothing
