query GetAccountInfoByRefreshToken($refreshToken: uuid!) {
	account(where: { refreshToken: { _eq: $refreshToken } }) {
		id
		type
		username
		beneficiaryId
		professionalId
		managerId
		adminStructureId
		professional {
			structure {
				deploymentId
			}
		}
		manager {
			deploymentId
		}
		admin_structure {
			deploymentId
		}
	}
}
