query GetProfessionalsForDeployment($deploymentId: uuid) {
	professional(where: { structure: { deploymentId: { _eq: $deploymentId } } }) {
		id
		firstname
		lastname
		mobileNumber
		position
		email
		structureId
		structure {
			id
			name
		}
	}
}
