mutation InsertAccountAdminStructure(
	$username: String!
	$accessKey: String!
	$accessKeyDate: timestamptz!
	$adminEmail: citext!
	$firstname: String
	$lastname: String
	$position: String
	$phoneNumbers: String
	$structureId: uuid!
) {
	account: insert_account_one(
		object: {
			username: $username
			type: admin_structure
			accessKey: $accessKey
			accessKeyDate: $accessKeyDate
			admin_structure: {
				data: {
					email: $adminEmail
					firstname: $firstname
					lastname: $lastname
					position: $position
					phoneNumbers: $phoneNumbers
					structures: { data: { structureId: $structureId } }
				}
			}
		}
	) {
		accessKey
		admin_structure {
			id
			email
			firstname
			lastname
		}
	}
}
