mutation InsertStructure(
  $name: citext!
  $phone: String
  $email: String
  $address1: String
  $address2: String
  $postalCode: String
  $city: String
  $website: String
  $siret: String
  $shortDesc: String
  $onConflict: structure_on_conflict
) {
  structure: insert_structure_one(
    on_conflict: $onConflict
    object: {
      name: $name
      phone: $phone
      email: $email
      address1: $address1
      address2: $address2
      postalCode: $postalCode
      city: $city
      website: $website
      siret: $siret
      shortDesc: $shortDesc
    }
  ) {
    id
  }
}
