query orientationInfos(
  $notebook_id: uuid!
  $structure_id: uuid!
  $with_new_referent: Boolean!
  $new_referent_account_id: uuid
) {
  notebook: notebook_public_view(where: { id: { _eq: $notebook_id } }) {
    beneficiary {
      id
      orientation_request: orientationRequest(
        where: { decidedAt: { _is_null: true } }
      ) {
        id
      }
      firstname
      lastname
      address1
      address2
      postalCode
      city
      cafNumber
      structures(where: { status: { _eq: "current" } }) {
        structureId
      }
    }
    former_referents: members(
      where: { memberType: { _eq: "referent" }, active: { _eq: true } }
    ) {
      account {
        id
        professional {
          firstname
          lastname
          email
          structure {
            name
          }
        }
      }
    }
  }
  newStructure: structure_by_pk(id: $structure_id) {
    name
  }
  newReferent: professional(
    where: { account: { id: { _eq: $new_referent_account_id } } }
  ) @include(if: $with_new_referent) {
    email
    firstname
    lastname
    structure {
      name
    }
  }
}
