query GetNotebook(
  $id: uuid!
  $eventsStart: timestamptz = "-infinity"
  $eventsEnd: timestamptz = "infinity"
  $withOrientationRequests: Boolean = true
) {
  refSituations: ref_situation {
    id
    description
    theme
  }
  notebook_public_view(where: { id: { _eq: $id } }) {
    id
    beneficiary {
      address1
      address2
      cafNumber
      city
      dateOfBirth
      email
      firstname
      id
      lastname
      mobileNumber
      peNumber
      postalCode
      rightAre
      rightAss
      rightBonus
      rightRsa
      externalDataInfos {
        external_data_id
        externalData {
          data
          source
        }
      }
      orientationRequest(order_by: { createdAt: desc }, limit: 1)
        @include(if: $withOrientationRequests) {
        id
        status
        createdAt
        decidedAt
        requestedOrientationSystem {
          name
          orientationType
        }
        decidedOrientationSystem {
          name
          orientationType
        }
        beneficiary {
          id
          notebook {
            id
          }
        }
      }
    }
    lastReferent: members(
      where: {
        _and: [
          { memberType: { _eq: "referent" } },
          { membershipEndedAt: { _is_null: false } }
        ]
      },
      order_by: { membershipEndedAt: desc_nulls_last},
      limit: 1) {
      id
      account {
        id
      }
    }
    members(where: { active: { _eq: true } }, order_by: { lastModifiedAt: desc_nulls_last }) {
      id
      memberType
      lastModifiedAt
      lastVisitedAt
      createdAt
      account {
        id
        type
        professional {
          id
          lastname
          firstname
          position
          email
          mobileNumber
          structure {
            id
            name
            address1
            address2
            postalCode
            city
            website
          }
        }
        orientation_manager {
          id
          lastname
          firstname
          email
          phoneNumbers
        }
      }
    }
    notebook {
      id
      beneficiaryId
      workSituationDate
      workSituationEndDate
      workSituation
      rightRqth
      educationLevel
      contractType
      contractSignDate
      contractStartDate
      contractEndDate
      lastJobEndedAt
      notebookInfo {
        needOrientation
        orientationReason
      }
      professionalProjects {
        id
        rome_code {
          id
          label
        }
        contract_type {
          id
          label
        }
        employment_type {
          id
          label
        }
        hourlyRate
        mobilityRadius
        updatedAt
        createdAt
        updater {
          orientation_manager {
            firstname
            lastname
          }
          professional {
            firstname
            lastname
            structure {
              name
            }
          }
        }
      }
      situations(where: { deletedAt: { _is_null: true } }, order_by: { createdAt: desc }) {
        id
        refSituation {
          id
          theme
          description
        }
        createdAt
        creator {
          orientation_manager {
            firstname
            lastname
          }
          professional {
            firstname
            lastname
            structure {
              name
            }
          }
        }
      }
      focuses(order_by: { theme: asc_nulls_last }) {
        id
        theme
        linkedTo
        createdAt
        creator {
          id
          professional {
            firstname
            lastname
            structure {
              name
            }
          }
          orientation_manager {
            id
            lastname
            firstname
          }
        }
        targets {
          id
          target
          actions_aggregate(where: { status: { _eq: "in_progress" } }) {
            aggregate {
              count
            }
          }
        }
      }
      appointments(
        where: { notebookId: { _eq: $id }, deleted_at: { _is_null: true } }
        distinct_on: memberAccountId
        order_by: [{ memberAccountId: asc }, { date: desc }]
      ) {
        date
        memberAccountId
      }
      events(
        order_by: { eventDate: desc_nulls_first }
        where: { eventDate: { _gte: $eventsStart, _lte: $eventsEnd } }
      ) {
        ...eventFields
      }
    }
  }
}

query GetNotebookEvents(
  $eventsStart: timestamptz = "-infinity"
  $eventsEnd: timestamptz = "infinity"
  $notebookId: uuid!
) {
  notebook_event(
    order_by: { eventDate: desc_nulls_last }
    where: { eventDate: { _gte: $eventsStart, _lte: $eventsEnd }, notebookId: { _eq: $notebookId } }
  ) {
    ...eventFields
  }
}

fragment eventFields on notebook_event {
  id
  eventDate
  event
  eventType
  creatorId
  creator {
    professional {
      structureId
      structure {
        name
      }
    }
  }
}
