mutation UpdateNotebookVisitDate($id: uuid!, $accountId: uuid!, $date: timestamptz!) {
  update_notebook_member(
    where: { notebookId: { _eq: $id }, accountId: { _eq: $accountId } }
    _set: { lastVisitedAt: $date }
  ) {
    returning {
      id
    }
  }
}
