query GetDeploymentStatForDay($day: timestamptz!, $last30Days: timestamptz!, $deploymentId: uuid!) {
  nbNotebooks: notebook_aggregate(
    where: { beneficiary: { deploymentId: { _eq: $deploymentId } } }
  ) {
    aggregate {
      count
    }
  }
  nbStructures: structure_aggregate(where: { deploymentId: { _eq: $deploymentId } }) {
    aggregate {
      count
    }
  }
  nbProfessionals: professional_aggregate(
    where: {
      structure: { deploymentId: { _eq: $deploymentId } }
      account: { deletedAt: { _is_null: true } }
    }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookWithActions: notebook_aggregate(
    where: { _or: [{ focuses: { targets: {} } }, { focuses: { targets: { actions: {} } } }] }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookModifiedSince30d: notebook_aggregate(
    where: {
      beneficiary: { deploymentId: { _eq: $deploymentId } }
      members: { lastModifiedAt: { _gte: $last30Days } }
    }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookCreatedToday: notebook_aggregate(
    where: { beneficiary: { deploymentId: { _eq: $deploymentId } }, createdAt: { _gte: $day } }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookVisitedToday: notebook_aggregate(
    where: {
      beneficiary: { deploymentId: { _eq: $deploymentId } }
      members: { lastVisitedAt: { _gte: $day } }
    }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookModifiedToday: notebook_aggregate(
    where: {
      beneficiary: { deploymentId: { _eq: $deploymentId } }
      members: { lastModifiedAt: { _gte: $day } }
    }
  ) {
    aggregate {
      count
    }
  }
  nbNotbookWith2MembersOrMore: notebook_aggregate(
    where: {
      members_aggregate: { count: { filter: { active: { _eq: true } }, predicate: { _gte: 2 } } }
      beneficiary: { deploymentId: { _eq: $deploymentId } }
    }
  ) {
    aggregate {
      count
    }
  }
  nbNotebookWithActionsCreated: notebook_aggregate(
    where: {
      beneficiary: { deploymentId: { _eq: $deploymentId } }
      focuses: {
        _or: [
          { createdAt: { _gte: $day } }
          {
            targets: {
              _or: [{ createdAt: { _gte: $day } }, { actions: { createdAt: { _gte: $day } } }]
            }
          }
        ]
      }
    }
  ) {
    aggregate {
      count
    }
  }
}
