query GetAccountsSummary {
	accounts: account(where: { type: { _eq: "professional" } }, order_by: { confirmed: asc }) {
		id
		confirmed
		professional {
			id
			firstname
			lastname
			position
			mobileNumber
			structure {
				id
				name
			}
		}
	}
}
