query GetBeneficiaries(
	$offset: Int!
	$limit: Int!
	$withMembers: beneficiary_bool_exp!
	$search: String!
) {
	search_beneficiaries_aggregate(args: { search: $search }, where: $withMembers) {
		aggregate {
			count
		}
	}
	beneficiaries: search_beneficiaries(
		args: { search: $search }
		limit: $limit
		offset: $offset
		order_by: [{ lastname: asc }, { firstname: asc }]
		where: $withMembers
	) {
		id
		firstname
		lastname
		needOrientation
		structures {
			structure {
				id
				name
			}
		}
		notebook {
			id
			members(where: { memberType: { _eq: "referent" } }, order_by: { createdAt: desc }) {
				id
				createdAt
				account {
					id
					professional {
						id
						firstname
						lastname
					}
				}
			}
		}
	}
}
