query GetNotebookInfo($id: uuid!) {
	notebook: notebook_by_pk(id: $id) {
		beneficiary {
			id
			firstname
			lastname
			dateOfBirth
			deployment {
				config
			}
		}
		members(where: { memberType: { _eq: "referent" } }) {
			professionalId
		}
	}
}
