mutation InsertAdminStructure(
	$adminEmail: citext
	$firstname: String
	$lastname: String
	$position: String
	$phoneNumbers: String
	$deploymentId: uuid
) {
	insert_admin_structure_one(
		object: {
			email: $adminEmail
			firstname: $firstname
			lastname: $lastname
			position: $position
			phoneNumbers: $phoneNumbers
			deploymentId: $deploymentId
		}
	) {
		id
	}
}
