mutation UpdateNotebookFromApi(
	$notebookId: uuid!
	$notebook: notebook_set_input
	$beneficiaryId: uuid!
	$beneficiary: beneficiary_set_input!
	$focuses: [notebook_focus_insert_input!]!
) {
	update_notebook_by_pk(pk_columns: { id: $notebookId }, _set: $notebook) {
		id
	}
	update_beneficiary_by_pk(pk_columns: { id: $beneficiaryId }, _set: $beneficiary) {
		id
	}
	insert_notebook_focus(objects: $focuses) {
		affected_rows
	}
}
