query getProfessionalOrientationOptions($professionalId: uuid!) {
  orientation: orientation_system(where: {professionalOrientationSystems: {professionalId: {_eq: $professionalId}}}) {
    id
    name
  }
}
