mutation UpdateNotebookContract(
  $id: uuid!
  $contractType: String!
  $contractSignDate: date!
  $contractStartDate: date!
  $contractEndDate: date!
) {
  update_notebook_by_pk(
    _set: {
      contractSignDate: $contractSignDate
      contractStartDate: $contractStartDate
      contractEndDate: $contractEndDate
      contractType: $contractType
    }
    pk_columns: { id: $id }
  ) {
    id
  }
}
