query GetStructureById($structureId: uuid!) {
  structure_by_pk(id: $structureId) {
    id
    siret
    name
    shortDesc
    phone
    email
    postalCode
    city
    address1
    address2
    website
    deployment {
      id
      label
    }
    orientationSystems {
      orientationSystem {
        id
      }
    }
  }
  orientation_system(
    where: { deployment: { structures: { id: { _eq: $structureId } } } }
    order_by: { name: asc }
  ) {
    id
    name
    orientationType
  }
}
