query GetStructureById($structureId: uuid!) {
  structure_by_pk(id: $structureId) {
    id
    siret
    name
    shortDesc
    phone
    email
    postalCode
    city
    address1
    address2
    website
    sensitive
    deployment {
      id
      label
      orientationSystems {
        id
        name
        orientationType
      }
    }
    orientationSystems {
      orientationSystem {
        id
      }
    }
  }
}
