mutation AddNotebookAppointment($date: date, $notebook_id: uuid, $professional_id: uuid, $status: String) {
  addAppointment: insert_notebook_appointment(
  	objects: {
  		date: $date,
  		notebook_id: $notebook_id,
  		professional_id: $professional_id,
  		status: $status
    }
  ) {
    returning {
      id
    }
  }
}
