mutation AddNotebookAppointment($date: date, $notebook_id: uuid, $professional_id: uuid, $status: String) {
  insert_notebook_appointment(
  	objects: {
  		date: $date,
  		notebook_id: $notebook_id,
  		professional_id: $professional_id,
  		status: $status}
  ) {
    id
  }
}
