query GetNotebookAppointments($professionalId: uuid, $notebookId: uuid) {
	getNotebookAppointments: notebook_appointment(
		where: { professional_id: { _eq: $professionalId }, notebook_id: { _eq: $notebookId } }
	) {
		date
		id
		status
	}
}
