query GetNotebookAppointments($professional_id: uuid, $notebook_id: uuid) {
  notebook_appointment(
  	where: {
  		professional_id: {
  			_eq: $professional_id
  		},
  		notebook_id: {
  			_eq: $notebook_id
  		}
  	}) {
			date
			id
			status
  }
}
