query GetNotebookAppointments($professionalId: uuid, $notebookId: uuid) {
	getNotebookAppointments: notebook_appointment(
		where: { professionalId: { _eq: $professionalId }, notebookId: { _eq: $notebookId } }
	) {
		date
		id
		status
	}
}
