alter table "public"."notebook_target" drop constraint "notebook_target_focus_id_target_key";
 
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestation liées à la CAF';
UPDATE public.notebook_target SET target='Travailler l’accès à la citoyenneté' WHERE target= 'Titre de séjour et pièces d''identité';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestation liées à la Sécurité sociale';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestations liées au RSA';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Obtenir une domiciliation';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Inscription scolaire et périscolaire';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestations liées aux ciasses de retraite';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestations liées à l''indemnisation du chômage (Pôle Emploi)';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Prestation liéées à l''ADPA';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Acquérir une autonomie sociale et budgétaire ou une mesure de protection';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Accéder à un droit';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Mise en œuvre des préconisations du travailleur social';
UPDATE public.notebook_target SET target='Accompagnement dans les démarches numériques' WHERE target= 'Accompagnement dans les démarches numériques';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Accéder à une aide alimentaire et un accompagnement';
UPDATE public.notebook_target SET target='Mise en place d''une mesure d''accompagnement adapté' WHERE target= 'Mise en place d''une mesure d''accompagnement adapté';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Domicialiation';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Démarches retraites';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Être accompagné dans les démarches d''accès au soin';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Démarches pour percevoir une pension alimentaire';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Aide juridictionnelle';
UPDATE public.notebook_target SET target='Travailler l’accès aux droits' WHERE target= 'Aide à l''obtention des justificatifs';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Accés à une allocation de retour à l''emploi';
UPDATE public.notebook_target SET target='Travailler l’accès à une prestation' WHERE target= 'Aide à la mobilité';
UPDATE public.notebook_target SET target='Mise en place d''une mesure d''accompagnement adapté' WHERE target= 'Rétablir la situation financière';
UPDATE public.notebook_target SET target='Réduire / apurer les dettes' WHERE target= 'Resoudre les difficultés financières';
UPDATE public.notebook_target SET target='Améliorer la gestion budgétaire' WHERE target= 'Acquérir des compétences techniques et administratives dans le but d''éviter l’aggravation de la situation financière';
UPDATE public.notebook_target SET target='Acquérir une autonomie budgétaire' WHERE target= 'Acquérir une autonomie sociale et budgétaire ou une mesure de protection';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Aide ou suivi pour la recherche d''emploi';
UPDATE public.notebook_target SET target='Développer son projet entreprenarial' WHERE target= 'Bilan professionnel et orientation';
UPDATE public.notebook_target SET target='Développer son projet entreprenarial' WHERE target= 'Création d''entreprise';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Reconversion professionnelle';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Prescription vers une action';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Accéder à  un CDDI';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Accéder à un emploi aidé';
UPDATE public.notebook_target SET target='Accéder à un 1er emploi' WHERE target= 'Inscription à Pôle Emploi';
UPDATE public.notebook_target SET target='Accéder à un 1er emploi' WHERE target= 'Inscription et/ou CAP Emploi';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Inscription sur actif51';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Inscription en agence d''intérim';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Inscription à l''agence Triangle';
UPDATE public.notebook_target SET target='Développer son projet entreprenarial' WHERE target= 'Faciliter le développement et la viabilité économique de l''activité';
UPDATE public.notebook_target SET target='Développer son projet entreprenarial' WHERE target= 'Mise en œuvre des préconisations d''une structure d''accompagnement spécialisée de type ADIE, CCI...';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Identifier ses freins liés à l''accès à l''emploi dans le domaine du sport et des loisirs.  Définir et mettre en œuvre un plan d''action permettant de lever ces freins.';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Identifier ses atouts et ses freins dans la recherche d''emploi et définir une stratégie de recherche d''emploi en adéquation avec le marché du travail';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Accèder rapidement à un emploi grâce à la mise en œuvre d''une stratégie de recherches d''emploi en adéquation avec le projet professionnel';
UPDATE public.notebook_target SET target='Accéder à un 1er emploi' WHERE target= 'Acquérir les compétences langagières nécessaires à la reprise d''un emploi';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Favoriser la mise en relation entre un candidat et un employeur  en aidant les bénéficiaires à mieux cibler les emplois de proximité';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Faciliter l''accès à l''emploi agricole';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Incription HUMANDO / SUEZ Insertion/Partage Travail';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Faciliter l''accès aux vendanges';
UPDATE public.notebook_target SET target='Bénéficier d''un suivi global' WHERE target= 'Proposer un accompagnement conjoint par le conseiller de Pôle emploi et le chargé de mission RSA du Département, permettant  de lever l''ensemble des freins et d''accèder à l''emploi';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Accèder à une qualification en lien avec les métiers en tension  (BTP, propreté, logistique, industrie,...)';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Etre accompagné pour redéfinir un projet professionnel, être accompagné pour développer et améliorer l''activité';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Evaluer ses capacités de retour à l''emploi / évaluer une orientation ESAT sur demande de la MDPH ou en amont d''une demande MDPH / bénéficier d''un accompagnement adapté à la RQTH';
UPDATE public.notebook_target SET target='Accéder à un 1er emploi' WHERE target= 'Acquérir les compétences langagières de base à une insertion';
UPDATE public.notebook_target SET target='Accéder à l’emploi' WHERE target= 'Accompagnement pour un placement direct à l''emploi';
UPDATE public.notebook_target SET target='Définir ou confirmer un projet professionnel' WHERE target= 'Définition d''un parcours de formation personnalisé';
UPDATE public.notebook_target SET target='Définir un parcours de formation personnalisé' WHERE target= 'Mobiliser l''ensemble des partenaires du SPIE et de nouveaux dispositifs concourant au rebond de l''usager';
UPDATE public.notebook_target SET target='Se former' WHERE target= 'Accéder à la formation';
UPDATE public.notebook_target SET target='Se former' WHERE target= 'Acquérir des compétences en entreprise favorisant l''employabilité';
UPDATE public.notebook_target SET target='Acquérir les compétences de bases' WHERE target= 'Acquérir les fondamentaux permettant la construction d''un parcours d''insertion';
UPDATE public.notebook_target SET target='Acquérir les compétences de bases' WHERE target= 'Accéder à la citoyenneté par une meilleure intégration sociale et culturelle';
UPDATE public.notebook_target SET target='Définir un parcours de formation personnalisé' WHERE target= 'Elaborer un parcours pédagogique favorisant l''insertion professionnelle';
UPDATE public.notebook_target SET target='Se remobiliser' WHERE target= 'Remobiliser les bénéficiaires du RSA dans un parcours d’insertion socio-professionnel.';
UPDATE public.notebook_target SET target='Acquérir les compétences de bases' WHERE target= 'Améliorer la connaissance des savoirs de base ou du potentiel de bénéficiaires du RSA';
UPDATE public.notebook_target SET target='Accéder au parcours d’accompagnement' WHERE target= 'Accéder au parcours d''accompagnement proposé dans le cadre de la Garantie Jeunes';
UPDATE public.notebook_target SET target='Définir un parcours de formation personnalisé' WHERE target= 'Accéder à un accompagnement';
UPDATE public.notebook_target SET target='Acquérir les compétences de bases' WHERE target= 'Acquérir et/ou développer des compétences et de l''expérience au travers d''une intégration au sein d''un collectif et d''une mission spécifique confiée aux jeunes';
UPDATE public.notebook_target SET target='Définir un parcours de formation personnalisé' WHERE target= 'Définition d''un parcours de formation personnalisé';
UPDATE public.notebook_target SET target='Se maintenir dans le logement' WHERE target= 'Accéder ou se maintenir dans un logement';
UPDATE public.notebook_target SET target='Se maintenir dans le logement' WHERE target= 'Se maintenir dans le logement suite à des impayés de loyers';
UPDATE public.notebook_target SET target='Changer de logement' WHERE target= 'Recherche de logement';
UPDATE public.notebook_target SET target='Se maintenir dans le logement' WHERE target= 'Amélioration de l''habitat pour faire face à une difficulté liée au handicap';
UPDATE public.notebook_target SET target='Se maintenir dans le logement' WHERE target= 'Maintent dans le logement';
UPDATE public.notebook_target SET target='Accéder à un logement' WHERE target= 'Accès au logement';
UPDATE public.notebook_target SET target='Réduire les impayés' WHERE target= 'Rupture ou risque de rupture Energie et fluides';
UPDATE public.notebook_target SET target='Rechercher un hébergement' WHERE target= 'Rupture effective de logement';
UPDATE public.notebook_target SET target='Se maintenir dans le logement' WHERE target= 'Litige autour du bail (autre que dettes)';
UPDATE public.notebook_target SET target='Se maintenir dans un hébergement' WHERE target= 'Hébergement';
UPDATE public.notebook_target SET target='Rechercher un hébergement' WHERE target= 'Recherche d''hébergement';
UPDATE public.notebook_target SET target='Se maintenir dans un hébergement' WHERE target= 'Maintient dans l''hébergement';
UPDATE public.notebook_target SET target='Recherche d''un hébergement' WHERE target= 'Trouver une solution d''hébergement';
UPDATE public.notebook_target SET target='Recherche d''un hébergement' WHERE target= 'Mise en œuvre des préconisations du chargé de mission logement ou travailleur social';
UPDATE public.notebook_target SET target='Réduire les impayés' WHERE target= 'Favoriser l''accès au logement ou la résorption d''un impayé';
UPDATE public.notebook_target SET target='Démarche de relogement suite à une problématique d''insalubrité ( DALO )' WHERE target= 'Habitat insalubre ou indécent (au sens du DALO)';
UPDATE public.notebook_target SET target='Démarche de relogement suite à une problématique d''insalubrité ( DALO )' WHERE target= 'Hébergement insablubre ou indécent (au sens du DALO)';
UPDATE public.notebook_target SET target='Améliorer la maitrise du français' WHERE target= 'Acquérir les compétences langagières de base à une insertion';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Accès à l''emploi - demande d''aide financière';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Identification et appui dans la réalisation des démarches/Relais  avec les partenaires/Mise en œuvre d''aides financières';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Favoriser l''accès aux dispositifs d''insertion sociale ou professionnel';
UPDATE public.notebook_target SET target='Bénéficier d''une aide financière pour l''achat de véhicule' WHERE target= 'Bénéficier d''une aide financière pour le passage du permis de conduire ou achat de véhicule';
UPDATE public.notebook_target SET target='Bénéficier d''une aide financière pour le passage du permis de conduire' WHERE target= 'Bénéficier d''un accompagnement pour le passage du code de la route';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Favoriser l''accès aux dispositifs d''insertion sociale ou professionnelle';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Favoriser l''accès aux dispositifs d''insertion sociale ou professionnel';
UPDATE public.notebook_target SET target='Obtenir le permis de conduire / code de la route' WHERE target= 'Acquérir les compétences garantissant la réussite au code et à l''examen de conduite';
UPDATE public.notebook_target SET target='Obtenir le permis de conduire / code de la route' WHERE target= 'Passer le Permis B';
UPDATE public.notebook_target SET target='Entretenir ou réparer son véhicule' WHERE target= 'Réparer sa voiture';
UPDATE public.notebook_target SET target='Bénéficier d''un accompagnement permettant d''accèder à la mobilité' WHERE target= 'Accès à l''emploi - demande d''aide financière';
UPDATE public.notebook_target SET target='Accéder aux droits' WHERE target= 'Dossier MDPH';
UPDATE public.notebook_target SET target='Accéder aux droits' WHERE target= 'Obtention du statut d''Aidant Familial';
UPDATE public.notebook_action SET action='Réalisation d’une demande à la préfecture' WHERE action= 'Dossier préfecture';
UPDATE public.notebook_action SET action='Réalisation d’une demande à la Caisse de retraite / complémentaires' WHERE action= 'Caisse de retraite et complémentaires';
UPDATE public.notebook_action SET action='L’accompagnement par les travailleurs sociaux en matière d''accès au droit' WHERE action= 'Aide au montage de dossiers administratifs';
UPDATE public.notebook_action SET action='Réalisation d’une demande de procédure judiciaire' WHERE action= 'Dossier procédure judiciaire';
UPDATE public.notebook_action SET action='L’accompagnement par les travailleurs sociaux en matière d''accès au droit' WHERE action= 'L''accompagnement social personnalisé';
UPDATE public.notebook_action SET action='Réalisation d’une demande APA, PCH…' WHERE action= 'APA, PCH,…';
UPDATE public.notebook_action SET action='Réalisation d’une demande à la Caisse de retraite / complémentaires' WHERE action= 'Démarches retraites';
UPDATE public.notebook_action SET action='Réalisation d’une demande de pension alimentaire' WHERE action= 'Démarches pour percevoir une pension alimentaire';
UPDATE public.notebook_action SET action='Réalisation d’une demande d’aide juridictionnelle' WHERE action= 'Aide juridictionnelle';
UPDATE public.notebook_action SET action='Réalisation d’une demande de domiciliation CERFA' WHERE action= 'Domiciliation';
UPDATE public.notebook_action SET action='Réalisation d’une demande de domiciliation CERFA' WHERE action= 'Cerfa - Demande de domiciliation';
UPDATE public.notebook_action SET action='Demande de protection administratives ou judiciaires ( MASP, tutelle, curatelle, sauvegarde de justice… )' WHERE action= 'Mesures de protection administratives ou judiciaires (MASP';
UPDATE public.notebook_action SET action='Réalisation d’une demande d’aide financière ou/et allocation Pôle emploi ( ARE, ASS… )' WHERE action= 'Dossier Pole emploi';
UPDATE public.notebook_action SET action='Réalisation d’une demande d’aide financière ou/et allocation Pôle emploi ( ARE, ASS… )' WHERE action= 'Accés à une allocation de retour à l''emploi';
UPDATE public.notebook_action SET action='Réalisation d’une demande de prestation ou / droit CAF/MSA ( allocation familiale, PAJE… )' WHERE action= 'Protocole CAF - Suspension AL / APL';
UPDATE public.notebook_action SET action='Réalisation d’une demande de prestation ou / droit CAF/MSA ( allocation familiale, PAJE… )' WHERE action= 'Dossier Caf';
UPDATE public.notebook_action SET action='Réalisation d’une demande de prestation ou / droit CAF/MSA ( allocation familiale, PAJE… )' WHERE action= 'CAF';
UPDATE public.notebook_action SET action='Réalisation d’une demande prestation ou aide de la Sécurité sociale  (indemnité journalière… )' WHERE action= 'Dossier accès aux droits à la santé (Puma';
UPDATE public.notebook_action SET action='Réalisation d’une demande prestation ou aide de la Sécurité sociale  (indemnité journalière… )' WHERE action= 'Sécurité sociale et mutuelle';
UPDATE public.notebook_action SET action='Réalisation d''une Déclaration Trimestrielle des Ressourcess revenues ( CAF, Pôle emploi… )' WHERE action= 'Déclaration trimestrielle des revenues';
UPDATE public.notebook_action SET action='Réalisation d''une Déclaration Trimestrielle des Ressourcess revenues ( CAF, Pôle emploi… )' WHERE action= 'Déclaration de situation';
UPDATE public.notebook_action SET action='Demande d’autres aides financières ( Département, CCAS, CAF, FAJ… )' WHERE action= 'FAG';
UPDATE public.notebook_action SET action='Demande d’autres aides financières ( Département, CCAS, CAF, FAJ… )' WHERE action= 'FAJ';
UPDATE public.notebook_action SET action='Demande d’autres aides financières ( Département, CCAS, CAF, FAJ… )' WHERE action= 'APA';
UPDATE public.notebook_action SET action='Demande d’autres aides financières ( Département, CCAS, CAF, FAJ… )' WHERE action= 'CCAS';
UPDATE public.notebook_action SET action='Mise en place d’un plan de surendettement' WHERE action= 'Aide à la constitution d''un dossier de surrendettement';
UPDATE public.notebook_action SET action='Réalisation d’un plan d’apurement dette' WHERE action= 'Aide et accompagnement à la résolution des dettes diverses';
UPDATE public.notebook_action SET action='Réalisation d’un plan d’apurement dette' WHERE action= 'Aide et accompagnement à la résolution des dettes diverses(FSL';
UPDATE public.notebook_action SET action='Mise en place d’une aide éducative budgétaire' WHERE action= 'L’accompagnement budgétaire';
UPDATE public.notebook_action SET action='L''accompagnement social personnalisé' WHERE action= 'L''accompagnement social personnalisé';
UPDATE public.notebook_action SET action='Mise en place d’une aide éducative budgétaire' WHERE action= 'Aide éducative budgétaire';
UPDATE public.notebook_action SET action='Mise en place d’une aide éducative budgétaire' WHERE action= 'Aide difficultés financières';
UPDATE public.notebook_action SET action='Orientation vers les partenaires entreprenariat ( CCI, ADIE… )' WHERE action= 'Accompagnement des TNS';
UPDATE public.notebook_action SET action='Orientation vers les partenaires entreprenariat ( CCI, ADIE… )' WHERE action= 'Suites accompagnement spécialisé TNS';
UPDATE public.notebook_action SET action='Orientation vers ACI' WHERE action= 'Orientation vers un Chantier d''insertion (ACI)';
UPDATE public.notebook_action SET action='Demande de CEC / CIE' WHERE action= 'CEC/CIE';
UPDATE public.notebook_action SET action='Inscription à Pôle emploi' WHERE action= 'Pôle Emploi';
UPDATE public.notebook_action SET action='Inscription à Cap emploi' WHERE action= 'CAP Emploi';
UPDATE public.notebook_action SET action='Orientation vers une plateforme partenaire' WHERE action= 'PAUPA';
UPDATE public.notebook_action SET action='Inscription en agence d’intérim' WHERE action= 'Inscription Interim';
UPDATE public.notebook_action SET action='Orientation vers une agence d’intérim' WHERE action= 'Partenariat intérim';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour identifier et lever les freins' WHERE action= 'Coaching Sport et Loisirs';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour accélérer la mise en emploi' WHERE action= 'Coaching';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour accélérer la mise en emploi' WHERE action= 'Coaching dipômés';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour accélérer la mise en emploi' WHERE action= 'Coaching intensif';
UPDATE public.notebook_action SET action='Orientation sur l''aide à la recherche d''emploi' WHERE action= 'PLATEFORME actif51';
UPDATE public.notebook_action SET action='Partenariat Chambre de l''agriculture / industrie / artisanat' WHERE action= 'Partenariat Chambre de l''agriculture';
UPDATE public.notebook_action SET action='Orientation sur les vendanges' WHERE action= 'RSA et Vendanges en Champagne';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour un recrutement dans les métiers en tension' WHERE action= 'Shaker';
UPDATE public.notebook_action SET action='Orientation vers un partenaire pour définir le projet professionnel' WHERE action= 'REAGIR';
UPDATE public.notebook_action SET action='Orientation vers la MDPH' WHERE action= 'Permanence du Jard';
UPDATE public.notebook_action SET action='Orientation vers un projet de Ville' WHERE action= 'Projet de ville';
UPDATE public.notebook_action SET action='Appui à la création d''entreprise' WHERE action= 'Appuie à la création d''entreprise';
UPDATE public.notebook_action SET action='Orientation SIAE' WHERE action= 'Orientation vers une SIAE';
UPDATE public.notebook_action SET action='Orientation PLIE' WHERE action= 'PLIE';
UPDATE public.notebook_action SET action='Orientation Prépa-Compétences' WHERE action= 'Prépa-Compétences';
UPDATE public.notebook_action SET action='Orientation vers une structure' WHERE action= 'Itinéraire Bis';
UPDATE public.notebook_action SET action='Recherche de formation' WHERE action= 'Recherche de formation';
UPDATE public.notebook_action SET action='Orientation vers une structure' WHERE action= 'Accompagnement MILO';
UPDATE public.notebook_action SET action='Orientation vers une structure' WHERE action= 'Le Partenariat Garantie Jeunes (expérimental)';
UPDATE public.notebook_action SET action='Orientation vers une formation' WHERE action= 'Parcours d''Acquisition des Compétences en Entreprise (PACE)';
UPDATE public.notebook_action SET action='Orientation vers un atelier' WHERE action= 'Atelier d''initiation aux savoirs de base numériques';
UPDATE public.notebook_action SET action='Orientation vers une formation' WHERE action= 'Activ''compétences';
UPDATE public.notebook_action SET action='Bilan de compétences' WHERE action= 'Diagnostics individuels approfondis (DIA)';
UPDATE public.notebook_action SET action='Prépa Compétences' WHERE action= 'Prépa compétences';
UPDATE public.notebook_action SET action='Ecole de la 2ème chance' WHERE action= 'Ecole de la 2ème chance';
UPDATE public.notebook_action SET action='Ateliers d''intégration à visée professionnelle' WHERE action= 'Ateliers d''intégration à visée professionnelle';
UPDATE public.notebook_action SET action='Linguistique : FLE' WHERE action= 'Linguistique : Alphabétisation';
UPDATE public.notebook_action SET action='Ateliers d''intégration à visée professionnelle' WHERE action= 'Action de redynamisation';
UPDATE public.notebook_action SET action='Demande d''aide au Fond de Solidarité pour le Logement' WHERE action= 'Demande Fonds Solidarité Logement';
UPDATE public.notebook_action SET action='Demande d''aide au Fond de Solidarité pour le Logement' WHERE action= 'Demande Fonds Solidarité Energie';
UPDATE public.notebook_action SET action='Demande DALO' WHERE action= 'Demande DALO - Démarche de relogement suite à une problématique d''insalubrité';
UPDATE public.notebook_action SET action='Demande d''hébergement ( SIAO )' WHERE action= 'Demande SIAO';
UPDATE public.notebook_action SET action='Participation à des formations / ateliers : amélioration des savoirs lecture / écriture' WHERE action= 'Ateliers socio-linguistiques Maison de quartier';
UPDATE public.notebook_action SET action='Participation à des formations / ateliers : Français Langue Étrangère' WHERE action= 'FLE';
UPDATE public.notebook_action SET action='Participation à des formations / ateliers : amélioration des savoirs lecture / écriture' WHERE action= 'Parcours langue';
UPDATE public.notebook_action SET action='Participation à des formations / ateliers : amélioration des savoirs lecture / écriture' WHERE action= 'Alphabétisation';
UPDATE public.notebook_action SET action='Inscription permis/code de la route( auto-école, internet… )' WHERE action= 'Passage du permis B (code et conduite)';
UPDATE public.notebook_action SET action='Inscription permis/code de la route( auto-école, internet… )' WHERE action= 'Inscrire en auto--écoel';
UPDATE public.notebook_action SET action='Inscription permis/code de la route( auto-école, internet… )' WHERE action= 'Préparation au code';
UPDATE public.notebook_action SET action='Mise à disposition de véhicules ( voiture, vélos électriques, trottinettes électriques… )' WHERE action= 'Location /Achat véhicule';
UPDATE public.notebook_action SET action='Prescription auprès d’un conseiller en mobilité' WHERE action= 'Coordonnatrice de Levée des Freins Périphériques';
UPDATE public.notebook_action SET action='Mobilisation du réseau de transport à la demande' WHERE action= 'La navette insertion';
UPDATE public.notebook_action SET action='Prescription auprès d’un conseiller en mobilité' WHERE action= 'Conseiller en mobilité inclusive';
UPDATE public.notebook_action SET action='Mise à disposition de véhicules ( voiture, vélos électriques, trottinettes électriques… )' WHERE action= 'Mise à disposition de voiture';
UPDATE public.notebook_action SET action='Constitution d’un dossier d’aide à la mobilité ( permis B, poids lourds… )' WHERE action= 'Demander l''aide à la mobilité';
UPDATE public.notebook_action SET action='Prescription auprès d’un conseiller en mobilité' WHERE action= 'Accès à l''emploi - info et conseil sur les offres';
UPDATE public.notebook_action SET action='Demander des chèques de mobilité' WHERE action= 'DAF sur chéquier mobilité  - IDF';
UPDATE public.notebook_action SET action='Mise en place du co-voiturage' WHERE action= 'co-voiturage';
UPDATE public.notebook_action SET action='Constitution d’un dossier d’aide à la mobilité ( permis B, poids lourds… )' WHERE action= 'aide à la mobilité du CCAS';
UPDATE public.notebook_action SET action='Constitution d’un dossier MDPH' WHERE action= 'Accompagnement à l''emploi de la pers. handicapée';

-- Copy actions from targets soon-to-be-removed duplicated targets 
INSERT INTO notebook_action(action, target_id, creator_id, status) 
SELECT A.action, Tg2.id, A.creator_id, 'in_progress'
FROM notebook_action A, notebook_target T, notebook_focus F, notebook_target Tg2 
WHERE A.target_id in (
    SELECT ID FROM
    (SELECT id, ROW_NUMBER() OVER (partition BY target, focus_id ORDER by id) AS nb FROM notebook_target) 
    T2 WHERE T2.nb > 1
) 
AND F.id = T.focus_id 
AND T.id = A.target_id 
AND Tg2.focus_id = F.id
AND T.target = Tg2.target
AND T.id <> tg2.id;

-- Remove duplicated actions
DELETE FROM notebook_action
WHERE ID in (
    SELECT ID FROM
    (SELECT id, ROW_NUMBER() OVER (partition BY action, target_id ORDER by id) AS nb FROM notebook_action) 
    A WHERE A.nb > 1
);

-- Remove duplicated targets
DELETE FROM notebook_target
WHERE ID in (
    SELECT ID FROM
    (SELECT id, ROW_NUMBER() OVER (partition BY target, focus_id ORDER by id) AS nb FROM notebook_target) 
    T WHERE T.nb > 1
);
 


-- Add constraint to avoid duplication action
alter table "public"."notebook_action" add constraint "notebook_action_target_id_action_key" unique ("target_id", "action");
alter table "public"."notebook_target" add constraint "notebook_target_focus_id_target_key" unique ("focus_id", "target");
-- Add default value to status
alter table "public"."notebook_action" alter column "status" set default 'in_progress';

--
-- insert migrations
--
TRUNCATE public.ref_situation;
TRUNCATE public.ref_target;
TRUNCATE public.ref_action;

INSERT INTO public.ref_situation (description, theme) VALUES('Contrainte horaires', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Autres contraintes', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Aidant familial ( s’occuper d’un proche )', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Attend un enfant ou plus', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Enfant(s) de moins de 3 ans sans solution de garde', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Enfant(s) en situation de handicap', 'contraintes_familiales');
INSERT INTO public.ref_target (description, theme) VALUES('Recherche de mode de garde', 'contraintes_familiales');
INSERT INTO public.ref_target (description, theme) VALUES('Devenir aidant familial salarié', 'contraintes_familiales');
INSERT INTO public.ref_target (description, theme) VALUES('Rompre l’isolement', 'contraintes_familiales');
INSERT INTO public.ref_action (description, theme) VALUES('Accès à un mode de garde', 'contraintes_familiales');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation de démarches visant à devenir obtenir le statut d''aidant', 'contraintes_familiales');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à des formations / ateliers : actions collectives de sociabilisassions', 'contraintes_familiales');
INSERT INTO public.ref_situation (description, theme) VALUES('Sans papiers d’identités, titre de séjour…', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Sans avis d’imposition', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Pas de sécurité sociale à jour', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Pas de mutuelle à jour', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Rencontre des difficultés sociales', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Difficulté à effectuer une démarche administrative', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Besoin d''être guidé dans le cadre d''un accès aux droits', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Autonome mais nécessitant d''être guidé dans le cadre d''un accès aux droits', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Rencontre des difficultés juridiques', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Absence d''équipement ou de connexion', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Absence d''adresse de messagerie', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Code d''accès et/ou mot de passe perdu', 'difficulte_administrative');
INSERT INTO public.ref_target (description, theme) VALUES('Travailler l’accès à une prestation', 'difficulte_administrative');
INSERT INTO public.ref_target (description, theme) VALUES('Travailler l’accès à la citoyenneté', 'difficulte_administrative');
INSERT INTO public.ref_target (description, theme) VALUES('Travailler l’accès aux droits', 'difficulte_administrative');
INSERT INTO public.ref_target (description, theme) VALUES('Accompagnement dans les démarches numériques', 'difficulte_administrative');
INSERT INTO public.ref_target (description, theme) VALUES('Mise en place d''une mesure d''accompagnement adapté', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('L’accompagnement par les travailleurs sociaux en matière d''accès au droit', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation autonome des démarches liées à l''accès aux droits', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Ecrivain Public Numérique', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande à la préfecture', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande à la Caisse de retraite / complémentaires', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande de procédure judiciaire', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande APA, PCH…', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande de pension alimentaire', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande d’aide juridictionnelle', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande de domiciliation CERFA', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de protection administratives ou judiciaires ( MASP, tutelle, curatelle, sauvegarde de justice… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande d’aide financière ou/et allocation Pôle emploi ( ARE, ASS… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande de prestation ou / droit CAF/MSA ( allocation familiale, PAJE… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande prestation ou aide de la Sécurité sociale  (indemnité journalière… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d''une Déclaration Trimestrielle des Ressourcess revenues ( CAF, Pôle emploi… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande de RSA / Prime d’activité', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réaliseration d’une demande pièce d’identité, titre de séjour, Etat civil…', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation de démarches pour obtenir le statut d’aidant familial', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une déclaration de situation ( CAF, Impôt… )', 'difficulte_administrative');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de CSS', 'difficulte_administrative');
INSERT INTO public.ref_situation (description, theme) VALUES('Inadéquation charges / ressources', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Incidents budgétaires ponctuels', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Difficulté dans la gestion d''un budget', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Baisse des ressources', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Ressources précaires ou ponctuelles', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Rupture alimentaire', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Sans aucune ressource', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('En situation de surendettement', 'difficulte_financiere');
INSERT INTO public.ref_target (description, theme) VALUES('Réduire / apurer les dettes', 'difficulte_financiere');
INSERT INTO public.ref_target (description, theme) VALUES('Améliorer la gestion budgétaire', 'difficulte_financiere');
INSERT INTO public.ref_target (description, theme) VALUES('Acquérir une autonomie budgétaire', 'difficulte_financiere');
INSERT INTO public.ref_target (description, theme) VALUES('Mettre en place une mesure de protection', 'difficulte_financiere');
INSERT INTO public.ref_target (description, theme) VALUES('Faire une demande de droits sociaux ( RSA, ASS… )', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Médiation avec les institutions', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Aide à la négociation ou renégociation de prêt', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Demande d’autres aides financières ( Département, CCAS, CAF, FAJ… )', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Mise en place d’un plan de surendettement', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’un plan d’apurement dette', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Mise en place d’une aide éducative budgétaire', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('L''accompagnement social personnalisé', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Demande d''aide alimentaire', 'difficulte_financiere');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de microcrédit social', 'difficulte_financiere');
INSERT INTO public.ref_situation (description, theme) VALUES('Inscrit à Pôle emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt  à suivre une formation', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Moins de 6 mois sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Plus de 6 mois sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Plus d''1 an sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Plus de 2 ans sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Plus de 5 ans sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Plus de 10 ans sans emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Jamais travaillé', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Disponible immédiatement', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Disponible à temps partiel', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt pour un emploi avec formations / accompagnement', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt mais pas pour n''importe quel emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Pas prêt pour un emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Ne sais pas s''il est prêt pour un emploi', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Autoentrepreneur / travailleur indépendant / conjoint collaborateur', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('En projet d''entreprise', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('En projet de profession libérale', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('RQTH - Rreconnaissance de la Qualité de Travailleur Handicapé', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder à l’emploi', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Développer son projet entreprenarial', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Définir ou confirmer un projet professionnel', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder à un 1er emploi', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Bénéficier d''un suivi global', 'emploi');
INSERT INTO public.ref_target (description, theme) VALUES('Découvrir un métier', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Accompagnement global', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Prestation Pole emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Autre', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers les partenaires entreprenariat ( CCI, ADIE… )', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers ACI', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de CEC / CIE', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Inscription à Pôle emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Inscription à Cap emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une plateforme partenaire', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Inscription en agence d’intérim', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une agence d’intérim', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un partenaire pour identifier et lever les freins', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un partenaire pour accélérer la mise en emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation sur l''aide à la recherche d''emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Partenariat Chambre de l''agriculture / industrie / artisanat', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers AI/ETTI', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation sur les vendanges', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un partenaire pour un recrutement dans les métiers en tension', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un partenaire pour définir le projet professionnel', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers la MDPH', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un projet de Ville', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Appui à la création d''entreprise', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation SIAE', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation PLIE', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation Prépa-Compétences', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une PMSMP', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’un stage', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à un forum emploi', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une alternance', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’un service civique', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Positionnement sur les clauses d''insertion', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Positionnement emploi adapté', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un ESAT', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Evaluation RQTH', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers EI', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers GEIC', 'emploi');
INSERT INTO public.ref_action (description, theme) VALUES('Comité Rebond', 'emploi');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt à en parler', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt pour une formation', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt pour une formation avec un accompagnement', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('Prêt pour un accompagnement', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('Ne sais pas s''il est prêt', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('A déjà identifié une formation', 'formation');
INSERT INTO public.ref_target (description, theme) VALUES('Définir un parcours de formation personnalisé', 'formation');
INSERT INTO public.ref_target (description, theme) VALUES('Se former', 'formation');
INSERT INTO public.ref_target (description, theme) VALUES('Acquérir les compétences de bases', 'formation');
INSERT INTO public.ref_target (description, theme) VALUES('Se remobiliser', 'formation');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder au parcours d’accompagnement', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une structure', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Recherche de formation', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une formation', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers un atelier', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Bilan de compétences', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Prépa Compétences', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Ecole de la 2ème chance', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Ateliers d''intégration à visée professionnelle', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation Cléa', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Atelier CV', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une formation certifiante', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation vers une formation qualifiante', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation EPIDE', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Orientation POEC', 'formation');
INSERT INTO public.ref_action (description, theme) VALUES('Linguistique : FLE', 'formation');
INSERT INTO public.ref_situation (description, theme) VALUES('Sans hébergement', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Hébergé chez un tiers', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Hébergé au domicile parental', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Logement insalubre', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Difficulté à payer le loyer', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Locataire parc social', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Locataire parc privé', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Logement de fortune (caravane, mobile home...)', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Propriétaire', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Doit quitter le logement', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Eloigné de tout', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Autre type de logement ( hôtel… )', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Hébergement collectif de type ( CHRS, CHU, CPH, CADA… )', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Rupture effective d''hébergemnt', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Accèder au logement social', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('S''informer sur les démarches liées au logement ( budget, état des lieux… )', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Se maintenir dans le logement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Changer de logement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder à un logement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Réduire les impayés', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Rechercher un hébergement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Se maintenir dans un hébergement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Recherche d''un hébergement', 'logement');
INSERT INTO public.ref_target (description, theme) VALUES('Démarche de relogement suite à une problématique d''insalubrité ( DALO )', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Appel 115', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de logement social', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Accompagnement par le chargé de mission logement', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Intervention face à une procédure expulsion', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Demande d''aide au Fond de Solidarité pour le Logement', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Demande DALO', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Demande d''hébergement ( SIAO )', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Accompagnement à la demande d’aide au logement ( APL, ALS… )', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Actions collectives liées au logement', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Demande DAHO', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation autonome des démarches liées au logement', 'logement');
INSERT INTO public.ref_action (description, theme) VALUES('Mesure d''Accompagnement Social Lié au Logement ( ASLL )', 'logement');
INSERT INTO public.ref_situation (description, theme) VALUES('Non maitrise de la langue française', 'maitrise_langue');
INSERT INTO public.ref_situation (description, theme) VALUES('Interprétariat nécessaire', 'maitrise_langue');
INSERT INTO public.ref_situation (description, theme) VALUES('Difficulté dans la lecture', 'maitrise_langue');
INSERT INTO public.ref_situation (description, theme) VALUES('Illectronisme', 'maitrise_langue');
INSERT INTO public.ref_target (description, theme) VALUES('Améliorer la maitrise du français', 'maitrise_langue');
INSERT INTO public.ref_target (description, theme) VALUES('Améliorer les savoirs : à l’écriture et la lecture', 'maitrise_langue');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à des formations / ateliers : amélioration des savoirs lecture / écriture', 'maitrise_langue');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à des formations / ateliers : Français Langue Étrangère', 'maitrise_langue');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation des heures OFII', 'maitrise_langue');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à des formations / ateliers : numériques', 'maitrise_langue');
INSERT INTO public.ref_situation (description, theme) VALUES('Autres permis ( poids lourds, bus… )', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Permis B', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Aucun moyen de transport à disposition', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Code obtenu', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Permis ou/et code en cours', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Dépendant des transports en communs', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Vélo ou trottinette électrique', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Véhicule ( voiture, moto, scooter )', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Permis non valide / Suspension permis', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Véhicule sans permis', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Co-voiturage', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder à un véhicule', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Bénéficier d''un accompagnement permettant d''accèder à la mobilité', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Bénéficier d''une aide financière pour le passage du permis de conduire', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Avoir accès aux transports en commun', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Bénéficier d''une aide financière pour l''achat de véhicule', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Obtenir le permis de conduire / code de la route', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Entretenir ou réparer son véhicule', 'mobilite');
INSERT INTO public.ref_target (description, theme) VALUES('Travailler la mobilité psychologique', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Bourse au permis', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Demander des chèques de mobilité', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Inscription permis/code de la route( auto-école, internet… )', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Mise à disposition de véhicules ( voiture, vélos électriques, trottinettes électriques… )', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Prescription auprès d’un conseiller en mobilité', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Mobilisation du réseau de transport à la demande', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Constitution d’un dossier d’aide à la mobilité ( permis B, poids lourds… )', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Mise en place du co-voiturage', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Mobilisation d’un garage solidaire', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d''une demande pour le permis, la carte grise…', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Constitution d’un dossier de financement pour l’achat d’un véhicule ( microcrédit… )', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Création d’une carte de transport en commun ( réseaux urbain / interurbain )', 'mobilite');
INSERT INTO public.ref_action (description, theme) VALUES('Demande de Carte Solidaire (Réduction SNCF, pass solidarité… )', 'mobilite');
INSERT INTO public.ref_situation (description, theme) VALUES('Absence de couverture / complémentaire sociale santé ( CSS, PUMa… )', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Problème de santé déclaré entravant l’exercice de certains métiers', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Problème de santé déclaré n’entravant pas la reprise d’une activité professionnelle', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Problème de santé déclaré entrainant des absences régulières', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Problème de santé déclaré ne permettant plus d’exercer une activité professionnelle', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Problème de santé déclaré ne permettant pas de reprendre une activité professionnelle immédiate', 'sante');
INSERT INTO public.ref_situation (description, theme) VALUES('Existence d''un dossier MDPH', 'sante');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder aux droits', 'sante');
INSERT INTO public.ref_target (description, theme) VALUES('Travailler sur les comportements de santé (dépendances, hygiène corporelle, dépistage… )', 'sante');
INSERT INTO public.ref_target (description, theme) VALUES('Accéder aux soins', 'sante');
INSERT INTO public.ref_target (description, theme) VALUES('Mettre en place une mesure de protection administrative ou juridique', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Constitution d’un dossier MDPH', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’une demande d’allocation ( APA… )', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation de démarches auprès de la Sécurité sociale ( CSS, AME… )', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’un bilan de santé', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Constitution d’un dossier d’invalidité auprès de la sécurité sociale', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Réalisation d’un suivi psychologique', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Mise en relation avec d’autres professionnels de santé', 'sante');
INSERT INTO public.ref_action (description, theme) VALUES('Participation à des groupes de soutien', 'sante');