name: "Setup Hasura CLI"
description: "Installs the Hasura CLI"
inputs:
  hasura-version:
    required: true
    description: "Hasura version"

runs:
  using: "composite"
  steps:
    - name: Install Hasura cli
      shell: bash
      run: |
        BIN_DIR="$HOME/.hasura/bin"
        mkdir -p "$BIN_DIR"
        curl --show-error --silent --fail --location --output "$BIN_DIR/hasura" https://github.com/hasura/graphql-engine/releases/download/v${{ inputs.hasura-version }}/cli-hasura-linux-amd64
        chmod +x "$BIN_DIR/hasura"
        echo "$BIN_DIR" >> "$GITHUB_PATH"
