query GetAccountsSummary {
  accounts: account(
    where: { type: { _in: [professional, orientation_manager] } }
    order_by: {
      type: asc
      confirmed: asc
      orientation_manager: { lastname: asc }
      professional: { lastname: asc }
    }
  ) {
    id
    type
    username
    lastLogin
    confirmed
    onboardingDone
    deletedAt
    orientation_manager {
      id
      firstname
      lastname
      email
      phoneNumbers
    }
    notebookCount: notebooksWhereMember_aggregate(
      where: { active: { _eq: true }, memberType: { _eq: "referent" } }
    ) {
      aggregate {
        count
      }
    }
    professional {
      id
      firstname
      lastname
      position
      mobileNumber
      email
      structure {
        id
        name
      }
    }
  }
}
