query GetNotebookMemberById($id: uuid!) {
	member: notebook_member_by_pk(id: $id) {
		notebookId
		creator {
			firstname
			lastname
			email
			id
		}
		professional {
			firstname
			lastname
			email
			id
			accounts {
				id
				confirmed
			}
		}
	}
}
