mutation UpdateNotebookVisitDate($notebookId: uuid!, $notebookVisitDate: timestamptz!) {
	update_notebook_member(
		where: { notebook: { id: { _eq: $notebookId } } }
		_set: { notebookVisitDate: $notebookVisitDate }
	) {
		returning {
			id
		}
	}
}

mutation UpdateNotebookContract($id: uuid!, $contractSignDate: date!, $contractType: String!) {
	update_notebook_by_pk(
		_set: { contractSignDate: $contractSignDate, contractType: $contractType }
		pk_columns: { id: $id }
	) {
		id
	}
}
