query GetNotebook($id: uuid!) {
	notebook: notebook_by_pk(id: $id) {
		id
		workSituationDate
		workSituation
		rightRsa
		rightRqth
		rightAre
		rightAss
		rightBonus
		geographicalArea
		job
		educationLevel
		contractType
		contractSignDate
		beneficiary {
			address1
			address2
			cafNumber
			city
			dateOfBirth
			email
			firstname
			id
			lastname
			mobileNumber
			peNumber
			postalCode
		}
		focuses(order_by: { theme: asc_nulls_last }) {
			id
			theme
			situations
			linkedTo
			targets {
				id
				target
			}
		}
		members(order_by: { notebookModificationDate: desc_nulls_last }) {
			id
			memberType
			notebookModificationDate
			notebookVisitDate
			professional {
				id
				lastname
				firstname
				position
				email
				mobileNumber
				structure {
					id
					name
					address1
					address2
					postalCode
					city
				}
			}
		}
	}
}
