mutation UpdateNotebookVisitDate($id: uuid!, $date: timestamptz!) {
	update_notebook_member(
		where: { notebook: { id: { _eq: $id } } }
		_set: { notebookVisitDate: $date }
	) {
		returning {
			id
		}
	}
}
