mutation AddNotebookAction($action: String!, $targetId: uuid!, $status: String!) {
  insert_notebook_action_one(object: { action: $action, targetId: $targetId, status: $status }) {
    id
    target {
      id
    }
  }
}
