query GetDiagnosticPE($notebookId: uuid!) {
  diagnostic_pole_emploi(notebookId: $notebookId) {
    besoinsParDiagnosticIndividuDtos {
      besoins {
        libelle
        valeur
      }
      idMetierChiffre
      nomMetier
      statut
      dateMiseAJour
    }
    contraintesIndividusDto {
      dateDeModification
      contraintes {
        libelle
        valeur
        objectifs {
          libelle
          valeur
        }
        situations {
          libelle
          valeur
        }
      }
    }
  }
}
