mutation AddNotebookAppointment(
  $date: timestamptz
  $notebookId: uuid
  $memberAccountId: uuid
  $status: String
) {
  addAppointment: insert_notebook_appointment(
    objects: {
      date: $date
      notebookId: $notebookId
      memberAccountId: $memberAccountId
      status: $status
    }
  ) {
    returning {
      id
      notebookId
    }
  }
}
