app:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  needs: [db]
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

app-backend:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: backend-sealed-secret
    - configMapRef:
        name: backend-configmap
  env:
    - name: APP_URL
      value: https://{{ .Values.global.host }}
    - name: GRAPHQL_API_URL
      value: https://hasura-{{ .Values.global.host }}/v1/graphql
    - name: BACKEND_API_URL
      value: https://api-{{ .Values.global.host }}
    - name: SENTRY_ENVIRONMENT
      value: '{{ .Values.global.env }}'
    - name: SENTRY_RELEASE
      value: '{{ .Values.global.branchSlug32 }}'

maildev: {}

jobs:
  enabled: true
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    - name: seed
      needs: [hasura]
      use: SocialGouv/kube-workflow/jobs/seed-db@v1
      with:
        seedPath: hasura/seeds/carnet_de_bord/seed-data.sql
