query GetManagedStructures($adminId: uuid!) {
  structures: structure(where: { admins: { adminStructureId: { _eq: $adminId } } }) {
    id
    city
    name
    beneficiaries_aggregate(where: { status: { _eq: "current" } }) {
      aggregate {
        count
      }
    }
    professionals_aggregate(where: { account: { deletedAt: { _is_null: true } } }) {
      aggregate {
        count
      }
    }
    admins_aggregate {
      aggregate {
        count
      }
    }
  }
}
