query GetAccountByPk($accountId: uuid!) {
  account_by_pk(id: $accountId) {
    id
    onboardingDone
    confirmed
    username
    type
    cguValidatedAt
    beneficiary {
      id
      firstname
      lastname
      email
      mobileNumber
      dateOfBirth
    }
    manager {
      id
      email
      firstname
      lastname
    }
    professional {
      id
      firstname
      lastname
      mobileNumber
      email
      position
      structure {
        id
        name
        address1
        address2
        postalCode
        city
        website
        deployment {
          label
        }
      }
    }
    admin_structure {
      id
      email
      firstname
      lastname
      position
      phoneNumbers
    }
    orientation_manager {
      id
      email
      firstname
      lastname
      phoneNumbers
    }
  }
}
