query GetDeploymentInfos($id: uuid!) {
	deployment: deployment_by_pk(id: $id) {
		label
	}
	beneficiaries: beneficiary_aggregate {
		aggregate {
			count
		}
	}
	beneficiariesWithNoStructure: beneficiary_aggregate(where: { _not: { structures: {} } }) {
		aggregate {
			count
		}
	}
	structures: structure_aggregate {
		aggregate {
			count
		}
	}
	structuresWithNoBeneficiary: structure_aggregate(where: { _not: { beneficiaries: {} } }) {
		aggregate {
			count
		}
	}
}
