query GetDeploymentInfos($id: uuid!) {
	deployment: deployment_by_pk(id: $id) {
		label
	}
	beneficiaries: beneficiary_aggregate {
		aggregate {
			count
		}
	}
	beneficiariesWithNoStructure: beneficiary_aggregate(
		where: { _and: [{ _not: { structures: {} } }, { notebook: { members: { _not: {} } } }] }
	) {
		aggregate {
			count
		}
	}
	structures: structure_aggregate(where: { deploymentId: { _eq: $id } }) {
		aggregate {
			count
		}
	}
	structuresWithPros: structure(where: { deploymentId: { _eq: $id } }) {
		id
		name
		professionals_aggregate {
			nodes {
				id
				email
				firstname
				lastname
			}
		}
	}
	structuresWithNoBeneficiary: structure_aggregate(
		where: {
			deploymentId: { _eq: $id }
			_not: { _or: [{ beneficiaries: {} }, { professionals: { notebooksWhereMember: {} } }] }
		}
	) {
		aggregate {
			count
		}
	}
}
