mutation ImportBeneficiary(
	$firstname: String!
	$lastname: String!
	$dateOfBirth: date!
	$mobileNumber: String
	$email: citext
	$address1: String
	$address2: String
	$postalCode: String
	$city: String
	$workSituation: String
	$cafNumber: String
	$peNumber: String
	$rightRsa: String
	$rightAre: Boolean
	$rightAss: Boolean
	$rightBonus: Boolean
	$rightRqth: Boolean
	$geographicalArea: String
	$job: String
	$educationLevel: String
	$internalId: String
	$deploymentId: uuid
	$members: [notebook_member_insert_input!]!
) {
	newNotebook: insert_notebook_one(
		object: {
			beneficiary: {
				data: {
					firstname: $firstname
					lastname: $lastname
					dateOfBirth: $dateOfBirth
					mobileNumber: $mobileNumber
					email: $email
					address1: $address1
					address2: $address2
					postalCode: $postalCode
					city: $city
					cafNumber: $cafNumber
					peNumber: $peNumber
					deploymentId: $deploymentId
				}
			}
			events: { data: [] }
			members: { data: $members }
			workSituation: $workSituation
			rightRsa: $rightRsa
			rightAre: $rightAre
			rightAss: $rightAss
			rightBonus: $rightBonus
			rightRqth: $rightRqth
			geographicalArea: $geographicalArea
			job: $job
			educationLevel: $educationLevel
			internalId: $internalId
		}
	) {
		id
	}
}
