-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."beneficiary_structure" add column "status" varchar
--  not null default 'pending';
