query GetLastVisitedOrUpdated($professionalId: uuid!) {
	lastVisited: notebook_member(
		order_by: { lastVisitedAt: desc_nulls_last }
		limit: 3
		where: { professionalId: { _eq: $professionalId }, lastVisitedAt: { _is_null: false } }
	) {
		notebook {
			id
			beneficiary {
				id
				firstname
				lastname
				mobileNumber
				dateOfBirth
			}
		}
	}
	lastUpdated: notebook_member(
		order_by: { lastModifiedAt: desc_nulls_last }
		limit: 3
		where: { professionalId: { _neq: $professionalId }, lastModifiedAt: { _is_null: false } }
	) {
		notebook {
			id
			beneficiary {
				id
				firstname
				lastname
				mobileNumber
				dateOfBirth
			}
		}
	}
}
