
mutation ReorientationRequest(
    $beneficiaryId: uuid!
    $reason: String
    $requestedOrientation: orientation_type_enum!
    ) {
  insert_orientation_request_one(object: {
    beneficiaryId: $beneficiaryId,
    reason: $reason,
    requestedOrientationTypeId: $requestedOrientation}) {
    id
  }
}
