query SearchNotebookMember(
	$professionalId: uuid!
	$filter: String
	$visitDate: timestamptz_comparison_exp!
) {
	notebook_member(
		where: {
			professionalId: { _eq: $professionalId }
			notebook: {
				beneficiary: {
					_or: [
						{ peNumber: { _ilike: $filter } }
						{ cafNumber: { _ilike: $filter } }
						{ lastname: { _ilike: $filter } }
						{ mobileNumber: { _ilike: $filter } }
					]
				}
			}
			notebookVisitDate: $visitDate
		}
		order_by: { notebookModificationDate: desc_nulls_first }
	) {
		id
		notebook {
			id
			beneficiary {
				dateOfBirth
				firstname
				id
				lastname
				mobileNumber
			}
		}
	}
}
