mutation INSERT_REF_DATA {
  insert_ref_situation(
    objects: [
      # LOGEMENT
      { theme: "logement", description: "Sans hébergement" }
      { theme: "logement", description: "CHRS" }
      { theme: "logement", description: "Hôtel social" }
      { theme: "logement", description: "Foyer d'urgence" }
      { theme: "logement", description: "Appartement relais" }
      { theme: "logement", description: "Bail glissant" }
      { theme: "logement", description: "Logement insalubre" }
      { theme: "logement", description: "Expulsion en cours" }
      { theme: "logement", description: "Difficulté à payer le loyer" }
      { theme: "logement", description: "Chez un tiers" }
      # DIFFICULTE FINANCIERE
      { theme: "difficulte_financiere", description: "Difficultés financières" }
      # DIFFICULTE ADMINISTRATIVE
      {
        theme: "difficulte_administrative"
        description: "Pas de carte d'identifié"
      }
      { theme: "difficulte_administrative", description: "Pas d'avis d'impot" }
      {
        theme: "difficulte_administrative"
        description: "Pas de titre de séjour à jour"
      }
      {
        theme: "difficulte_administrative"
        description: "Pas de sécurité sociale à jour"
      }
      { theme: "difficulte_administrative", description: "Pas de CSS" }
      {
        theme: "difficulte_administrative"
        description: "Difficultés juridiques"
      }
      { theme: "difficulte_administrative", description: "Accès au droit" }
      # MOBILITE
      { theme: "mobilite", description: "Pas d'accès aux transports en commun" }
      { theme: "mobilite", description: "Pas de permis valide" }
      { theme: "mobilite", description: "Permis B mais sans véhicule" }
      { theme: "mobilite", description: "Mobile à vélo" }
      {
        theme: "mobilite"
        description: "Aucun moyen de transport à disposition"
      }
    ]
  ) {
    affected_rows
  }
}

mutation INSERT_REF_TARGET {
  insert_ref_target(
    objects: [
      # LOGEMENT
      {
        theme: "logement"
        description: "Recherche d'un logement"
        actions: {
          data: [
            { description: "Demande SIAO" }
            { description: "Demande de logement social" }
            {
              description: "Demande DALO - Démarche de relogement suite à une problématique d'insalubrité"
            }
          ]
        }
      }
      {
        theme: "logement"
        description: "Se maintenir dans le logement suite à des impayés de loyers"
        actions: {
          data: [
            { description: "Demande Fonds Solidarité Energie" }
            { description: "Demande Fonds Solidarité Logement" }
          ]
        }
      }
      # DIFFICULTE FINANCIERE
      {
        theme: "difficulte_financiere"
        description: "Résoudre les difficultés financières"
        actions: {
          data: [
            {
              description: "Aide à la constitution du dossier de surendettement"
            }
            { description: "Médiation avec les institutions" }
            { description: "Aide à la négociation ou renégociation de prêt" }
            {
              description: "Aide et accompagnement à la résolution des dettes diverses"
            }
            { description: "Aide éducative budgétaire" }
            { description: "Aide difficultés financières" }
          ]
        }
      }
      # DIFFICULTE ADMINISTRATIVE
      {
        theme: "difficulte_administrative"
        description: "Obtenir une domiciliation"
        actions: { data: [{ description: "Cerfa - Demande de domiciliation" }] }
      }
      {
        theme: "difficulte_administrative"
        description: "Accés à une allocation de retour à l'emploi"
        actions: {
          data: [
            { description: "Déclaration trimestrielle des revenues" }
            { description: "Déclaration de situation" }
          ]
        }
      }
      { theme: "difficulte_administrative", description: "Démarches retraites" }
      {
        theme: "difficulte_administrative"
        description: "Démarches pour percevoir une pension alimentaire"
      }
      {
        theme: "difficulte_administrative"
        description: "Aide juridictionnelle"
      }
      { theme: "difficulte_administrative", description: "Accés à la mobilité" }
      {
        theme: "difficulte_administrative"
        description: "Aide à l'obtention des justificatifs"
      }
      # FREIN MOBILITE
      {
        theme: "mobilite"
        description: "Avoir accès aux transport en commun"
        actions: {
          data: [
            { description: "Demander l'Aide à la mobilité" }
            { description: "Demander des Chèques mobilité" }
          ]
        }
      }
      {
        theme: "mobilite"
        description: "Passer le permis B"
        actions: { data: [{ description: "Inscrire en auto-école" }] }
      }
      {
        theme: "mobilite"
        description: "Réparer sa voiture"
        actions: { data: [{ description: "Demander l'Aide à la mobilité" }] }
      }
      {
        theme: "mobilite"
        description: "Accéder à une voiture"
        actions: {
          data: [
            { description: "Mise à disposition de voiture" }
            { description: "Co-voiturage" }
          ]
        }
      }
    ]
  ) {
    affected_rows
  }
}
