query GetProfessionalsForManager {
  professional(where: { account: { deletedAt: { _is_null: true } } }) {
    id
    firstname
    lastname
    mobileNumber
    position
    email
    structureId
    account {
      id
    }
    structure {
      id
      name
    }
  }
}
