query GetStructuresWithPro {
  structure {
    id
    name
    professionals(where: { account: { deletedAt: { _is_null: true } } }) {
      account {
        referentCount: notebooksWhereMember_aggregate(
          where: { memberType: { _eq: "referent" }, active: { _eq: true } }
        ) {
          aggregate {
            count
          }
        }
        id
      }
      id
      firstname
      lastname
      mobileNumber
      position
      email
      structureId
      structure {
        id
        name
      }
    }
  }
}
