query GetBeneficiaries(
  $offset: Int! = 0
  $limit: Int! = 20
  $where: beneficiary_bool_exp! = {}
  $search: String! = ""
) {
  search_beneficiaries_aggregate(args: { search: $search }, where: $where) {
    aggregate {
      count
    }
  }
  beneficiaries: search_beneficiaries(
    args: { search: $search }
    limit: $limit
    offset: $offset
    order_by: [{ lastname: asc }, { firstname: asc }]
    where: $where
  ) {
    id
    firstname
    lastname
    dateOfBirth
    notebook {
      notebookInfo {
        orientationSystem {
          name
          orientationType
        }
        needOrientation
      }
    }
    structures(where: { status: { _neq: "outdated" } }) {
      structure {
        id
        name
      }
    }
    notebook {
      id
      members(
        where: { active: { _eq: true }, memberType: { _in: ["orientation_manager", "referent"] } }
        order_by: { createdAt: desc }
      ) {
        id
        createdAt
        account {
          id
          type
          orientation_manager {
            id
            firstname
            lastname
          }
          professional {
            id
            firstname
            lastname
          }
        }
      }
    }
  }
}
