mutation UpdateOrientationManager(
  $objects: [notebook_member_insert_input!]!
  $beneficiaries: [uuid!]!
) {
  update_notebook_member(
    _set: { active: false, membershipEndedAt: now }
    where: {
      memberType: { _eq: "orientation_manager" }
      notebook: { beneficiaryId: { _in: $beneficiaries } }
      active: { _eq: true }
    }
  ) {
    affected_rows
  }

  insert_notebook_member(objects: $objects) {
    affected_rows
  }
}
