mutation UpdateStructure(
	$id: uuid
	$name: String!
	$phone: String!
	$email: String!
	$address1: String!
	$address2: String!
	$postalCode: String!
	$city: String!
	$website: String!
	$siret: String!
	$shortDesc: String!
) {
	structure: update_structure(
		where: { id: { _eq: $id } }
		_set: {
			name: $name
			phone: $phone
			email: $email
			address1: $address1
			address2: $address2
			postalCode: $postalCode
			city: $city
			website: $website
			siret: $siret
			shortDesc: $shortDesc
		}
	) {
		returning {
			id
			name
			phone
			email
			address1
			address2
			postalCode
			city
			website
			siret
			shortDesc
		}
	}
}
