query GetDeploymentInfos($id: uuid!) {
  deployment: deployment_by_pk(id: $id) {
    label
  }
  beneficiaries: beneficiary_aggregate(where: { notebook: {} }) {
    aggregate {
      count
    }
  }
  beneficiariesWithNoStructure: beneficiary_aggregate(
    where: { notebook: {}, _not: { structures: { status: { _eq: "current" } } } }
  ) {
    aggregate {
      count
    }
  }
  structures: structure_aggregate {
    aggregate {
      count
    }
  }
  structuresWithPros: structure {
    id
    name
    professionals(where: { account: { deletedAt: { _is_null: true } } }) {
      id
      email
      firstname
      lastname
      account {
        id
      }
    }
  }
  structuresWithNoBeneficiary: structure_aggregate(
    where: {
      _and: [
        { _not: { beneficiaries: { status: { _eq: "current" } } } }
        {
          _not: { professionals: { account: { notebooksWhereMember: { active: { _eq: true } } } } }
        }
      ]
    }
  ) {
    aggregate {
      count
    }
  }
}
