query GetAccountById($id: uuid!) {
  account: account_by_pk(id: $id) {
    id
    username
    confirmed
    type
    deletedAt
    orientation_manager {
      firstname
      lastname
      email
    }
    professional {
      firstname
      lastname
      email
    }
  }
}
