query ($notebookId: uuid!) {
  situations: notebook_situation(where: { notebookId: { _eq: $notebookId }, deletedAt: {_is_null: false} }) {
    creator {
      orientation_manager {
        lastname
        firstname
      }
      professional {
        structure {
          name
        }
        lastname
        firstname
      }
    }
    createdAt
    refSituation {
      description
      theme
    }
  }
}
