mutation CreateBeneficiaryAccount($username: String!, $beneficiaryId: uuid!) {
	insert_account_one(
		object: {
			username: $username
			beneficiaryId: $beneficiaryId
			type: beneficiary
			confirmed: true
		}
	) {
		id
	}
}
