query BeneficiariesWithOrientationRequest {
  beneficiaries: beneficiary(
    where: { orientationRequest: { decidedAt: { _is_null: true } } }
  ) {
    id
    firstname
    lastname
    structures(where: { status: { _neq: "outdated" } }) {
      structure {
        id
        name
      }
    }
    orientationRequest {
      id
      requestedOrientationType {
        label
      }
      decidedOrientationType {
        label
      }
      reason
      createdAt
    }
    notebook {
      id
      notebookInfo {
        orientationType {
          label
        }
      }
      members(
        where: { active: { _eq: true }, memberType: { _in: ["orientation_manager", "referent"] } }
        order_by: { createdAt: desc }
      ) {
        account {
          id
          type
          professional {
            id
            firstname
            lastname
          }
          orientation_manager {
            id
            firstname
            lastname
          }
        }
      }
    }
  }
}
