query BeneficiariesWithOrientationRequest {
  beneficiaries: beneficiary(
    where: { orientationRequest: { decidedOrientationTypeId: { _is_null: true } } }
  ) {
    id
    firstname
    lastname
    structures {
      structure {
        id
        name
      }
    }
    orientationRequest {
      id
      requestedOrientationType {
        label
      }
      decidedOrientationType {
        label
      }
      reason
      createdAt
    }
    beneficiaryInfo {
      orientation
    }
    notebook {
      id
      members(
        where: { active: { _eq: true }, memberType: { _in: ["orientation_manager", "referent"] } }
        order_by: { createdAt: desc }
      ) {
        account {
          id
          type
          professional {
            id
            firstname
            lastname
          }
          orientation_manager {
            id
            firstname
            lastname
          }
        }
      }
    }
  }
}
