query GetBeneficiariesWithOrientationRequest(
  $offset: Int! = 0
  $limit: Int! = 20
  $where: beneficiary_bool_exp! = {}
  $search: String! = ""
) {
  search_beneficiaries_aggregate(args: { search: $search }, where: $where) {
    aggregate {
      count
    }
  }
  beneficiaries: search_beneficiaries(
    args: { search: $search }
    limit: $limit
    offset: $offset
    order_by: [{ lastname: asc }, { firstname: asc }]
    where: $where
  ) {
    id
    firstname
    lastname
    dateOfBirth
    city
    structures(where: { status: { _neq: "outdated" } }) {
      structure {
        id
        name
      }
    }
    orientationRequest(order_by: { createdAt: desc }, limit: 1) {
      id
      requestedOrientationSystem {
        name
        orientationType
      }
      decidedOrientationSystem {
        name
        orientationType
      }
      reason
      createdAt
    }
    notebook {
      id
      notebookInfo {
        orientationSystem {
          name
          orientationType
        }
      }
      referent: members(
        where: { active: { _eq: true }, memberType: { _eq: "referent" } }
        order_by: { createdAt: desc }
      ) {
        id
        account {
          id
          professional {
            id
            firstname
            lastname
          }
        }
      }
      orientationManager: members(
        where: { active: { _eq: true }, account: { type: { _eq: orientation_manager } } }
        order_by: { createdAt: desc }
      ) {
        id
        account {
          id
          orientation_manager {
            id
            firstname
            lastname
          }
        }
      }
    }
  }
}
