query GetPendingBeneficiaries($structureId: uuid!) {
	structure_by_pk(id: $structureId) {
		beneficiaries(
			where: {
				status: { _eq: "pending" }
				beneficiary: {
					notebook: {
						_or: [
							{ _not: { members: {} } }
							{ members: { professional: { structureId: { _neq: $structureId } } } }
						]
					}
				}
			}
			order_by: { beneficiary: { lastname: asc } }
		) {
			beneficiary {
				firstname
				lastname
				dateOfBirth
				notebook {
					id
				}
			}
		}
	}
}
