query GetPendingBeneficiaries($structureId: uuid!) {
	structure_by_pk(id: $structureId) {
		beneficiaries(
			where: {
				beneficiary: {
					notebook: { members: { professional: { structureId: { _neq: $structureId } } } }
				}
			}
			order_by: { beneficiary: { lastname: asc } }
		) {
			beneficiary {
				firstname
				lastname
				dateOfBirth
				notebook {
					id
				}
			}
		}
	}
}
