-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Admin_structure_structure exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


adminStructureId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Admin_structure_structure
adminStructureId =
    Object.selectionForField "ScalarCodecs.Uuid" "adminStructureId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
admin_structure :
    SelectionSet decodesTo CdbGQL.Object.Admin_structure
    -> SelectionSet decodesTo CdbGQL.Object.Admin_structure_structure
admin_structure object____ =
    Object.selectionForCompositeField "admin_structure" [] object____ Basics.identity


createdAt : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.Admin_structure_structure
createdAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "createdAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


deletedAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Admin_structure_structure
deletedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "deletedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Admin_structure_structure
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
structure :
    SelectionSet decodesTo CdbGQL.Object.Structure
    -> SelectionSet decodesTo CdbGQL.Object.Admin_structure_structure
structure object____ =
    Object.selectionForCompositeField "structure" [] object____ Basics.identity


structureId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Admin_structure_structure
structureId =
    Object.selectionForField "ScalarCodecs.Uuid" "structureId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)
