-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Beneficiary_structure exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
beneficiary :
    SelectionSet decodesTo CdbGQL.Object.Beneficiary
    -> SelectionSet decodesTo CdbGQL.Object.Beneficiary_structure
beneficiary object____ =
    Object.selectionForCompositeField "beneficiary" [] object____ Basics.identity


beneficiaryId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Beneficiary_structure
beneficiaryId =
    Object.selectionForField "ScalarCodecs.Uuid" "beneficiaryId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


createdAt : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.Beneficiary_structure
createdAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "createdAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


type alias DataOptionalArguments =
    { path : OptionalArgument String }


{-|

  - path - JSON select path

-}
data :
    (DataOptionalArguments -> DataOptionalArguments)
    -> SelectionSet CdbGQL.ScalarCodecs.Jsonb CdbGQL.Object.Beneficiary_structure
data fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { path = Absent }

        optionalArgs____ =
            [ Argument.optional "path" filledInOptionals____.path Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "ScalarCodecs.Jsonb" "data" optionalArgs____ (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecJsonb |> .decoder)


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Beneficiary_structure
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


status : SelectionSet String CdbGQL.Object.Beneficiary_structure
status =
    Object.selectionForField "String" "status" [] Decode.string


{-| An object relationship
-}
structure :
    SelectionSet decodesTo CdbGQL.Object.Structure
    -> SelectionSet decodesTo CdbGQL.Object.Beneficiary_structure
structure object____ =
    Object.selectionForCompositeField "structure" [] object____ Basics.identity


structureId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Beneficiary_structure
structureId =
    Object.selectionForField "ScalarCodecs.Uuid" "structureId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


updatedAt : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.Beneficiary_structure
updatedAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updatedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)
