-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.External_data_info exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
beneficiary :
    SelectionSet decodesTo CdbGQL.Object.Beneficiary
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.External_data_info
beneficiary object____ =
    Object.selectionForCompositeField "beneficiary" [] object____ (Basics.identity >> Decode.nullable)


beneficiary_id : SelectionSet (Maybe CdbGQL.ScalarCodecs.Uuid) CdbGQL.Object.External_data_info
beneficiary_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "beneficiary_id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


created_at : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.External_data_info
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
externalData :
    SelectionSet decodesTo CdbGQL.Object.External_data
    -> SelectionSet decodesTo CdbGQL.Object.External_data_info
externalData object____ =
    Object.selectionForCompositeField "externalData" [] object____ Basics.identity


external_data_id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.External_data_info
external_data_id =
    Object.selectionForField "ScalarCodecs.Uuid" "external_data_id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


professional_id : SelectionSet (Maybe CdbGQL.ScalarCodecs.Uuid) CdbGQL.Object.External_data_info
professional_id =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "professional_id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


updated_at : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.External_data_info
updated_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "updated_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)
