-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.External_data exposing (..)

import CdbGQL.Enum.External_source_enum
import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


created_at : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.External_data
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


type alias DataOptionalArguments =
    { path : OptionalArgument String }


{-|

  - path - JSON select path

-}
data :
    (DataOptionalArguments -> DataOptionalArguments)
    -> SelectionSet CdbGQL.ScalarCodecs.Jsonb CdbGQL.Object.External_data
data fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { path = Absent }

        optionalArgs____ =
            [ Argument.optional "path" filledInOptionals____.path Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "ScalarCodecs.Jsonb" "data" optionalArgs____ (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecJsonb |> .decoder)


{-| An object relationship
-}
externalDataInfo :
    SelectionSet decodesTo CdbGQL.Object.External_data_info
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.External_data
externalDataInfo object____ =
    Object.selectionForCompositeField "externalDataInfo" [] object____ (Basics.identity >> Decode.nullable)


{-| An object relationship
-}
external_source :
    SelectionSet decodesTo CdbGQL.Object.External_source
    -> SelectionSet decodesTo CdbGQL.Object.External_data
external_source object____ =
    Object.selectionForCompositeField "external_source" [] object____ Basics.identity


hash : SelectionSet String CdbGQL.Object.External_data
hash =
    Object.selectionForField "String" "hash" [] Decode.string


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.External_data
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


source : SelectionSet CdbGQL.Enum.External_source_enum.External_source_enum CdbGQL.Object.External_data
source =
    Object.selectionForField "Enum.External_source_enum.External_source_enum" "source" [] CdbGQL.Enum.External_source_enum.decoder


updated_at : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.External_data
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
