-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Notebook_situation exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


createdAt : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.Notebook_situation
createdAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "createdAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


createdBy : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_situation
createdBy =
    Object.selectionForField "ScalarCodecs.Uuid" "createdBy" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
creator :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_situation
creator object____ =
    Object.selectionForCompositeField "creator" [] object____ (Basics.identity >> Decode.nullable)


deletedAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_situation
deletedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "deletedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


deletedBy : SelectionSet (Maybe CdbGQL.ScalarCodecs.Uuid) CdbGQL.Object.Notebook_situation
deletedBy =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "deletedBy" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


{-| An object relationship
-}
deletor :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_situation
deletor object____ =
    Object.selectionForCompositeField "deletor" [] object____ (Basics.identity >> Decode.nullable)


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_situation
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
notebook :
    SelectionSet decodesTo CdbGQL.Object.Notebook
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_situation
notebook object____ =
    Object.selectionForCompositeField "notebook" [] object____ (Basics.identity >> Decode.nullable)


notebookId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_situation
notebookId =
    Object.selectionForField "ScalarCodecs.Uuid" "notebookId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
refSituation :
    SelectionSet decodesTo CdbGQL.Object.Ref_situation
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_situation
refSituation object____ =
    Object.selectionForCompositeField "refSituation" [] object____ (Basics.identity >> Decode.nullable)


situationId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_situation
situationId =
    Object.selectionForField "ScalarCodecs.Uuid" "situationId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)
