-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Notebook_event_type_min_fields exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


comment : SelectionSet (Maybe String) CdbGQL.Object.Notebook_event_type_min_fields
comment =
    Object.selectionForField "(Maybe String)" "comment" [] (Decode.string |> Decode.nullable)


value : SelectionSet (Maybe String) CdbGQL.Object.Notebook_event_type_min_fields
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)
