-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Notebook_appointment exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
account :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet decodesTo CdbGQL.Object.Notebook_appointment
account object____ =
    Object.selectionForCompositeField "account" [] object____ Basics.identity


{-| An object relationship
-}
accountByDeletedBy :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_appointment
accountByDeletedBy object____ =
    Object.selectionForCompositeField "accountByDeletedBy" [] object____ (Basics.identity >> Decode.nullable)


created_at : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_appointment
created_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "created_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


date : SelectionSet CdbGQL.ScalarCodecs.Timestamp CdbGQL.Object.Notebook_appointment
date =
    Object.selectionForField "ScalarCodecs.Timestamp" "date" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


deleted_at : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_appointment
deleted_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "deleted_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


deleted_by : SelectionSet (Maybe CdbGQL.ScalarCodecs.Uuid) CdbGQL.Object.Notebook_appointment
deleted_by =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "deleted_by" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_appointment
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


memberAccountId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_appointment
memberAccountId =
    Object.selectionForField "ScalarCodecs.Uuid" "memberAccountId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
notebook :
    SelectionSet decodesTo CdbGQL.Object.Notebook
    -> SelectionSet decodesTo CdbGQL.Object.Notebook_appointment
notebook object____ =
    Object.selectionForCompositeField "notebook" [] object____ Basics.identity


notebookId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_appointment
notebookId =
    Object.selectionForField "ScalarCodecs.Uuid" "notebookId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


status : SelectionSet String CdbGQL.Object.Notebook_appointment
status =
    Object.selectionForField "String" "status" [] Decode.string


updated_at : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_appointment
updated_at =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "updated_at" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)
