-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Notebook_member exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| An object relationship
-}
account :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet decodesTo CdbGQL.Object.Notebook_member
account object____ =
    Object.selectionForCompositeField "account" [] object____ Basics.identity


accountId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_member
accountId =
    Object.selectionForField "ScalarCodecs.Uuid" "accountId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


active : SelectionSet Bool CdbGQL.Object.Notebook_member
active =
    Object.selectionForField "Bool" "active" [] Decode.bool


createdAt : SelectionSet CdbGQL.ScalarCodecs.Timestamptz CdbGQL.Object.Notebook_member
createdAt =
    Object.selectionForField "ScalarCodecs.Timestamptz" "createdAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
creator :
    SelectionSet decodesTo CdbGQL.Object.Account
    -> SelectionSet (Maybe decodesTo) CdbGQL.Object.Notebook_member
creator object____ =
    Object.selectionForCompositeField "creator" [] object____ (Basics.identity >> Decode.nullable)


creatorId : SelectionSet (Maybe CdbGQL.ScalarCodecs.Uuid) CdbGQL.Object.Notebook_member
creatorId =
    Object.selectionForField "(Maybe ScalarCodecs.Uuid)" "creatorId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder |> Decode.nullable)


id : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_member
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


invitationSendAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_member
invitationSendAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "invitationSendAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


lastModifiedAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_member
lastModifiedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "lastModifiedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


lastVisitedAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_member
lastVisitedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "lastVisitedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


memberType : SelectionSet String CdbGQL.Object.Notebook_member
memberType =
    Object.selectionForField "String" "memberType" [] Decode.string


membershipEndedAt : SelectionSet (Maybe CdbGQL.ScalarCodecs.Timestamptz) CdbGQL.Object.Notebook_member
membershipEndedAt =
    Object.selectionForField "(Maybe ScalarCodecs.Timestamptz)" "membershipEndedAt" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder |> Decode.nullable)


{-| An object relationship
-}
notebook :
    SelectionSet decodesTo CdbGQL.Object.Notebook
    -> SelectionSet decodesTo CdbGQL.Object.Notebook_member
notebook object____ =
    Object.selectionForCompositeField "notebook" [] object____ Basics.identity


notebookId : SelectionSet CdbGQL.ScalarCodecs.Uuid CdbGQL.Object.Notebook_member
notebookId =
    Object.selectionForField "ScalarCodecs.Uuid" "notebookId" [] (CdbGQL.ScalarCodecs.codecs |> CdbGQL.Scalar.unwrapCodecs |> .codecUuid |> .decoder)
