-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module CdbGQL.Object.Professional_project_var_samp_fields exposing (..)

import CdbGQL.InputObject
import CdbGQL.Interface
import CdbGQL.Object
import CdbGQL.Scalar
import CdbGQL.ScalarCodecs
import CdbGQL.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| in cents (divide by 100 for the EUR value)
-}
hourlyRate : SelectionSet (Maybe Float) CdbGQL.Object.Professional_project_var_samp_fields
hourlyRate =
    Object.selectionForField "(Maybe Float)" "hourlyRate" [] (Decode.float |> Decode.nullable)


mobilityRadius : SelectionSet (Maybe Float) CdbGQL.Object.Professional_project_var_samp_fields
mobilityRadius =
    Object.selectionForField "(Maybe Float)" "mobilityRadius" [] (Decode.float |> Decode.nullable)
