query getProfessionalsForOrientationSystemAndDeployment(
  $deploymentId: uuid!
  $orientationSystemId: uuid!
) {
  professional(
    where: {
      _and: [
        { orientationSystems: { orientationSystemId: { _eq: $orientationSystemId } } }
        { structure: { deploymentId: { _eq: $deploymentId } } }
      ]
    }
  ) {
    firstname
    lastname
    account {
      id
      referentCount: notebooksWhereMember_aggregate(
        where: { memberType: { _eq: "referent" }, active: { _eq: true } }
      ) {
        aggregate {
          count
        }
      }
    }
    structure {
      id
      name
      professionals {
        account {
          referentCount: notebooksWhereMember_aggregate(
            where: { memberType: { _eq: "referent" }, active: { _eq: true } }
          ) {
            aggregate {
              count
            }
          }
        }
      }
    }
  }
}
