query GetLastVisitedOrUpdated($accountId: uuid!) {
	lastVisited: notebook_member(
		order_by: { lastVisitedAt: desc_nulls_last }
		limit: 3
		where: { accountId: { _eq: $accountId }, lastVisitedAt: { _is_null: false } }
	) {
		notebook {
			id
			beneficiary {
				id
				firstname
				lastname
				mobileNumber
				dateOfBirth
			}
		}
	}
	lastUpdated: notebook_member(
		order_by: { lastModifiedAt: desc_nulls_last }
		limit: 3
		where: { accountId: { _eq: $accountId }, lastModifiedAt: { _is_null: false } }
	) {
		notebook {
			id
			beneficiary {
				id
				firstname
				lastname
				mobileNumber
				dateOfBirth
			}
		}
	}
}
