query GetLastVisitedOrUpdated($accountId: uuid!) {
  notebook(
    order_by: [
      { beneficiary: { lastname: asc_nulls_first } }
      { beneficiary: { firstname: asc_nulls_first } }
    ]
  ) {
    id
    members(where: { accountId: { _eq: $accountId } }) {
      accountId
      lastVisitedAt
      lastModifiedAt
      active
      memberType
    }
    beneficiary {
      id
      firstname
      lastname
      mobileNumber
      dateOfBirth
      orientationRequest(order_by: { createdAt: desc }, limit: 1) {
        id
        status
        createdAt
        decidedAt
        requestedOrientationSystem {
          name
          orientationType
        }
      }
    }
  }
}
