mutation updateStructure(
  $id: uuid!
  $address1: String
  $address2: String
  $postalCode: String
  $city: String
  $website: String
  $shortDesc: String
  $siret: String
  $phone: String
  $name: citext
  $email: String
  $orientationSystemsToAdd: [structure_orientation_system_insert_input!]!
  $orientationSystemsToDelete: [uuid!]
) {
  update_structure_by_pk(
    pk_columns: { id: $id }
    _set: {
      address1: $address1
      address2: $address2
      city: $city
      email: $email
      name: $name
      phone: $phone
      postalCode: $postalCode
      shortDesc: $shortDesc
      siret: $siret
      website: $website
    }
  ) {
    id
  }
  delete_structure_orientation_system(
    where: {
      _and: [
        { structureId: { _eq: $id } }
        { orientationSystemId: { _in: $orientationSystemsToDelete } }
      ]
    }
  ) {
    affected_rows
  }
  insert_structure_orientation_system(objects: $orientationSystemsToAdd) {
    affected_rows
  }
  delete_professional_orientation_system(
    where: {
      _and: [
        { professional: { structureId: { _eq: $id } } }
        { orientationSystemId: { _in: $orientationSystemsToDelete } }
      ]
    }
  ) {
    affected_rows
  }
}
