query GetStructure($structureId: uuid!) {
  structure_by_pk(id: $structureId) {
    id
    name
    phone
    email
    address1
    address2
    postalCode
    city
    website
    supportedBeneficiaries: beneficiaries_aggregate(
      where: {
        status: { _neq: "outdated" }
        beneficiary: {
          notebook: {
            members: {
              active: { _eq: true }
              memberType: { _eq: "referent" }
              account: { professional: { structureId: { _eq: $structureId } } }
            }
          }
        }
      }
    ) {
      aggregate {
        count
      }
    }
    unsupportedBeneficiaries: beneficiaries_aggregate(
      where: {
        status: { _neq: "outdated" }
        beneficiary: {
          notebook: {
            _not: {
              members: {
                active: { _eq: true }
                memberType: { _eq: "referent" }
                account: { professional: { structureId: { _eq: $structureId } } }
              }
            }
          }
        }
      }
    ) {
      aggregate {
        count
      }
    }
    professionals {
      id
      account {
        id
      }
      email
      firstname
      lastname
    }
    professionals_aggregate(where: { account: { deletedAt: { _is_null: true } } }) {
      aggregate {
        count
      }
    }
    admins_aggregate {
      nodes {
        admin_structure {
          id
          email
          firstname
          lastname
          phoneNumbers
        }
      }
    }
  }
}
