query GetStructure($structureId: uuid!) {
  beneficiaries: notebook_aggregate(
    where: {
      members: {
        active: { _eq: true }
        account: { professional: { structureId: { _eq: $structureId } } }
      }
    }
  ) {
    aggregate {
      count
    }
  }
  structure_by_pk(id: $structureId) {
    id
    name
    phone
    email
    address1
    address2
    postalCode
    city
    website
    beneficiaries: beneficiaries_aggregate(
      where: {
        status: { _neq: "outdated" }
        beneficiary: {
          notebook: {
            _not: {
              members: {
                active: { _eq: true }
                account: { professional: { structureId: { _eq: $structureId } } }
              }
            }
          }
        }
      }
    ) {
      aggregate {
        count
      }
    }
    professionals(where: { account: { deletedAt: { _is_null: true } } }) {
      id
      account {
        id
      }
      email
      firstname
      lastname
    }
    professionals_aggregate(where: { account: { deletedAt: { _is_null: true } } }) {
      aggregate {
        count
      }
    }
    admins_aggregate {
      nodes {
        admin_structure {
          id
          email
          firstname
          lastname
          phoneNumbers
        }
      }
    }
  }
}
