mutation InsertOrientationRequest(
  $beneficiaryId: uuid!
  $reason: String
  $requestedOrientationSystemId: uuid!
) {
  insert_orientation_request_one(
    object: {
      beneficiaryId: $beneficiaryId
      reason: $reason
      requestedOrientationSystemId: $requestedOrientationSystemId
    }
  ) {
    id
  }
}
