---
name: Deploy storybook

on:
  workflow_dispatch:
  push:
    branches:
      - chore/deploy-storybook
    tags:
      - '*'

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - run: cd app && npm ci
      - name: Deploy storybook to Github Pages
        run: cd app && npm run deploy-storybook -- --ci --source-branch=chore/deploy-storybook
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
