name: Scalingo review app creation

on:
  pull_request:
    types: [opened, reopened]

concurrency:
  cancel-in-progress: true
  group: review-scalingo-${{ github.ref }}

jobs:
  scalingo-link:
    name: Link Scalingo review apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Scalingo CLI
        run: |
          BIN_DIR="$HOME/bin"
          mkdir -p $BIN_DIR
          PATH=$BIN_DIR:$PATH
          echo "$BIN_DIR" >> "$GITHUB_PATH"
          wget https://cli-dl.scalingo.com/install
          bash ./install -i $BIN_DIR

      - name: Run linking script
        env:
          SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
          SUFFIX: -review-pr${{ github.event.number }}
        run: |
          ./scripts/link-scalingo-apps.sh
  add-pull-request-comment:
    name: Add review app URL to Pull Request
    runs-on: ubuntu-latest
    needs: [scalingo-link]
    steps:
      - name: Add review app URL
        uses: blablacar/action-sticky-description@master
        with:
          issue_number: ${{ github.event.number }}
          marker: "## REVIEW APP URL PLACEHOLDER ##"
          message: |
            Se rendre sur la [review app](https://cdb-app-review-pr${{ github.event.number }}.osc-fr1.scalingo.io).
