name: Test

on:
  push:
    branches-ignore:
      - "master"
    tags-ignore:
      - v*
env:
  HASURA_VERSION: 2.12.0
  POETRY_VERSION: 1.1.13
  PYTHON_VERSION: 3.10

concurrency:
  cancel-in-progress: true
  group: test-${{ github.ref }}

jobs:
  ##############################################################################
  ## Python backend tests
  ##############################################################################
  pytest:
    name: run pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Hasura CLI
        uses: ./.github/actions/hasura-cli
        with:
          hasura-version: $HASURA_VERSION

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.5
        with:
          poetry-version: $POETRY_VERSION
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install

      - name: Run pytest
        run: |
          cp .env.test.sample .env.test
          ./scripts/launch_tests.sh python

  ##############################################################################
  ## End To End Tests
  ##############################################################################
  e2e:
    name: run CodeceptJS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        run: |
          cd app && yarn install --prefer-offline --frozen-lockfile && cd -
          cd e2e && yarn install --prefer-offline --frozen-lockfile && cd -

      - name: Install Hasura CLI
        uses: ./.github/actions/hasura-cli
        with:
          hasura-version: $HASURA_VERSION

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: $PYTHON_VERSION
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.5
        with:
          poetry-version: $POETRY_VERSION
      - name: Install Python dependencies
        working-directory: ./backend
        run: poetry install

      - name: Run test e2e
        run: |
          cp .env.test.sample .env.test
          ./scripts/launch_tests.sh e2e

      - name: Copy artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: e2e/output

  ##############################################################################
  ## Functional Tests (endpoints & hasura)
  ##############################################################################
  functional_tests:
    name: run functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn
          cache-dependency-path: "app/yarn.lock"

      - name: Install dependencies
        run: |
          cd app
          yarn install --prefer-offline --frozen-lockfile

      - name: Install Hasura CLI
        uses: ./.github/actions/hasura-cli
        with:
          hasura-version: $HASURA_VERSION

      - name: Run functional tests
        run: |
          cp .env.test.sample .env.test
          ./scripts/launch_tests.sh js
