-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."orientation_request" add column "decision_reason" text
--  null;
